### ISSUE TITLE
Preparing "Install NDK (Side by side) 21.3.6528147

### ISSUE THREAD

**Issue by SAVE-POlNT** [beeware/toga#1144]
hello guys , 
i wanted to test beeware for the first time and i have a problem / bug i do not really know , i searched but it looks like no one had this issue before , so u ran the installations smoothly i am using python3.8 and requests 25 and this is my problem
case build android
---------------------------------------------------------------------------------------
[test] Building Android APK...
Starting a Gradle Daemon (subsequent builds will be faster)
Compatible side by side NDK version was not found.
Checking the license for package NDK (Side by side) 21.3.6528147 in /home/mehdi/.briefcase/tools/android_sdk/licenses
License for package NDK (Side by side) 21.3.6528147 accepted.
Preparing "Install NDK (Side by side) 21.3.6528147 (revision: 21.3.6528147)".
<=============> 100% CONFIGURING [17m 42s]
---------------------------------------------------------------------------------------
this configuration is taking forever by the time m talking it is 21 mins so should i let it take its time or i have t reinstall everyting on a tested python version like 3.7 or 3.6 ?

**Comment by freakboy3742** [comment]
This is completely expected. Unfortunately, the UI during this step is *really* bad - but it's also completely out of our control. At this point in the process, Gradle is downloading the Native developer kit (NDK); the time it takes will depend entirely on your internet connection, but even on my relatively fast broadband connection, it takes over 10 minutes.  During this entire time, the UI says "100% Configuring".

This is [mentioned in the BeeWare tutorial](https://docs.beeware.org/en/latest/tutorial/tutorial-5/android.html#create-an-android-app-and-compile-it) (see the note "Gradle may look stuck").''

Closing since the question should be resolved.

**Comment by CarterSnich** [comment]
How to know if it's completely done downloading and installing? Coz, when I do `briefcase run android` I got this error and it downloads NDK again: 

`(beeware-venv) D:\Users\Joe Mar\Documents\BeeWare\beeware-tutorial\helloworld>briefcase run android
Downloading the Android emulator and system image...
Warning: File D:\Users\Joe Mar\.android\repositories.cfg could not be loaded.   
[=======================================] 100% Unzipping... emulator/resources/m
[helloworld] Building Android APK...
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details
Compatible side by side NDK version was not found.
Warning: Still waiting for package manifests to be fetched remotely.
Warning: IO exception while downloading manifest:
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
        at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.openUrl(DownloadCache.java:247)
        at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.downloadAndCache(DownloadCache.java:624)
        at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.openCachedUrl(DownloadCache.java:455)
        at com.android.sdklib.repository.legacy.LegacyDownloader.downloadAndStream(LegacyDownloader.java:61)
        at com.android.repository.impl.downloader.LocalFileAwareDownloader.downloadAndStream(LocalFileAwareDownloader.java:51)
        at com.android.repository.impl.manager.RemoteRepoLoaderImpl.lambda$fetchPackages$0(RemoteRepoLoaderImpl.java:149)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Warning: IO exception while downloading manifest:
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
        at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.openUrl(DownloadCache.java:247)
        at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.downloadAndCache(DownloadCache.java:624)
        at com.android.sdklib.repository.legacy.remote.internal.DownloadCache.openCachedUrl(DownloadCache.java:455)
        at com.android.sdklib.repository.legacy.LegacyDownloader.downloadAndStream(LegacyDownloader.java:61)
        at com.android.repository.impl.downloader.LocalFileAwareDownloader.downloadAndStream(LocalFileAwareDownloader.java:51)
        at com.android.repository.impl.manager.RemoteRepoLoaderImpl.lambda$fetchPackages$0(RemoteRepoLoaderImpl.java:149)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
<=============> 100% Warning: Still waiting for package manifests to be fetched remotely.
Checking the license for package NDK (Side by side) 22.1.7171670 in D:\Users\Joe Mar\.briefcase\tools\android_sdk\licenses
License for package NDK (Side by side) 22.1.7171670 accepted.
Preparing "Install NDK (Side by side) 22.1.7171670 (revision: 22.1.7171670)".
<=============> 100% CONFIGURING [3m 25s]
> IDLE`



I had already took 50 mins downloading it after I run `briefcase create android`, so it should already be installed, right?

**Comment by freakboy3742** [comment]
@CarterSnich It's impossible to say. 50 minutes is definitley a long time, but it will depend on your connection speed. There's multiple gigabytes that need to be downloaded, so it's not out of the question that it might take 50 minutes. It takes almost 20  minutes on my connection, and I get a fairly consistent 50MBit. 

The good news is that this is only needed on the first run - after the downloads have completed, they'll be re-used on future builds. The bad news is that the UX on Google's tools seem to assume that you're on a Gigabit fibre, and the download won't take more than a few seconds - because the download status updates are awful - and there's not much we can do about that, because the download process is managed by Android's tooling.

I will say that the warnings in your log message aren't encouraging... it does suggest that there's been a failure of some kind during the download process.

**Comment by CarterSnich** [comment]
> @CarterSnich It's impossible to say. 50 minutes is definitley a long time, but it will depend on your connection speed. There's multiple gigabytes that need to be downloaded, so it's not out of the question that it might take 50 minutes. It takes almost 20 minutes on my connection, and I get a fairly consistent 50MBit.
> 
> The good news is that this is only needed on the first run - after the downloads have completed, they'll be re-used on future builds. The bad news is that the UX on Google's tools seem to assume that you're on a Gigabit fibre, and the download won't take more than a few seconds - because the download status updates are awful - and there's not much we can do about that, because the download process is managed by Android's tooling.
> 
> I will say that the warnings in your log message aren't encouraging... it does suggest that there's been a failure of some kind during the download process.

I was checking the OpenJDK process on the task manager as well. Since it stopped using the internet and it's not using any CPU resource so I assumed that the installation was done. My last resort is manually download NDK, but I don't know the path where it should be installed.

**Comment by CarterSnich** [comment]
> @CarterSnich It's impossible to say. 50 minutes is definitley a long time, but it will depend on your connection speed. There's multiple gigabytes that need to be downloaded, so it's not out of the question that it might take 50 minutes. It takes almost 20 minutes on my connection, and I get a fairly consistent 50MBit.
> 
> The good news is that this is only needed on the first run - after the downloads have completed, they'll be re-used on future builds. The bad news is that the UX on Google's tools seem to assume that you're on a Gigabit fibre, and the download won't take more than a few seconds - because the download status updates are awful - and there's not much we can do about that, because the download process is managed by Android's tooling.
> 
> I will say that the warnings in your log message aren't encouraging... it does suggest that there's been a failure of some kind during the download process.

Thank you for your response. Can I just manually download and install NDK? What are the other things to be downloaded after NDK?

**Comment by CarterSnich** [comment]
I installed the NDK manually. Exactly the same version what BeeWare is trying to download (for those who are having the same problem, it's the "Preparing . . ." line):
```
License for package NDK (Side by side) 22.1.7171670 accepted.
Preparing "Install NDK (Side by side) 22.1.7171670 (revision: 22.1.7171670)".
<=============> 100% CONFIGURING [3m 25s]
```
Just copy and paste the quoted `"Install NDK (Side by side) 22.1.7171670 (revision: 22.1.7171670)"` and google it.

I now able to create my very first Android app. Kuddos to @freakboy3742 and to others who contributed to this project.

**Comment by BADBISHOP700** [comment]
with a size of over 700mb i think its better to download and install it manually

**Comment by subhasishdas159** [comment]
stuck at 28% for 6 minutes. Not sure if it's crashed or running.

**Comment by freakboy3742** [comment]
@subhasishdas159 As this thread and the tutorial both point out, 6 minutes is not the least bit unusual. The UX around this is awful, and unfortunately, not under our control - Google's developers apparently assume everyone is sitting on a multi-gigabyte fibre connection with no latency.
