### ISSUE TITLE
AttributeError: 'CSS' object has no attribute 'bind'

### ISSUE THREAD

**Issue by Ksengine** [beeware/toga#1146]
**run this code**
```python
import toga

web = toga.WebView(url='https://google.com')
```

**full error log**
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/toga_gtk/widgets/webview.py", line 24, in __init__
    super().__init__(id=id, style=style, url=url, on_key_down=on_key_down)
  File "/usr/local/lib/python3.7/dist-packages/toga/interface/widgets/webview.py", line 29, in __init__
    super(WebView, self).__init__(id=id, style=style, url=url, on_key_down=on_key_down, on_webview_load=None)
  File "/usr/local/lib/python3.7/dist-packages/toga/interface/widgets/base.py", line 144, in __init__
    self.style = CSS()
  File "/usr/local/lib/python3.7/dist-packages/toga/interface/widgets/base.py", line 170, in style
    self._style = value.bind(self)
AttributeError: 'CSS' object has no attribute 'bind'
```
**Environment:**
 - Operating System: Armbian Debian armv7(arm32)
 - Python version: cpython 3.7.7 pre-installed on system
 - Software versions:
   - Toga: 0.2.15

**Very bad error.**

**Comment by freakboy3742** [comment]
Looks like you're running Toga 0.2. We're no longer supporting the 0.2 branch; all develop and bug reports should be against the 0.3 branch.

**Comment by Ksengine** [comment]
I had installed from pip

**Comment by freakboy3742** [comment]
Yes. You installed the 0.2 branch from pip. If you read the tutorial and documentation, it tells you that you need to specify `--pre` option when installing toga.

**Comment by Ksengine** [comment]
thanks
