### ISSUE TITLE
CSS object has no attribute 'bind'

### ISSUE THREAD

**Issue by stuaxo** [beeware/toga#1202]
I tried installing toga-demo and running it but hit an error.

```
$ pip install toga-demo
$ toga-demo
Traceback (most recent call last):
  File "/home/stu/.local/lib/python3.8/site-packages/toga_gtk/app.py", line 116, in _startup
    self.startup()
  File "/home/stu/.local/lib/python3.8/site-packages/toga_demo/app.py", line 15, in startup
    left_container = toga.OptionContainer()
  File "/home/stu/.local/lib/python3.8/site-packages/toga_gtk/widgets/optioncontainer.py", line 13, in __init__
    super(OptionContainer, self).__init__(id=id, style=style, content=content)
  File "/home/stu/.local/lib/python3.8/site-packages/toga/interface/widgets/optioncontainer.py", line 22, in __init__
    super().__init__(id=id, style=style, content=content)
  File "/home/stu/.local/lib/python3.8/site-packages/toga/interface/widgets/base.py", line 144, in __init__
    self.style = CSS()
  File "/home/stu/.local/lib/python3.8/site-packages/toga/interface/widgets/base.py", line 170, in style
    self._style = value.bind(self)

```

**Comment by freakboy3742** [comment]
Thanks for the report. That error occurs when you're running the 0.2 branch of toga. The 0.2 branch is essentially unmaintained at this point - or, at least, we're not focussing on any bugs that exist. You need to use the `--pre` option when running any `pip` commands so you get the 0.3 development branch.
