### ISSUE TITLE
'MultilineTextInput' on iOS fails with "object has no attribute '_value'"

### ISSUE THREAD

**Issue by massenz** [beeware/toga#1231]
**Describe the bug**
Attempting to create a MultilineTextInput on iOS fails at construction

**To Reproduce**
1. Use the example from the reference docs: `textbox = toga.MultilineTextInput(id='view1')`
2. Start app on emulator
3. App crashes with statcktrace (see below) and error:
```
AttributeError: 'MultilineTextInput' object has no attribute '_value'
```

**Expected behavior**
Having a Multiline text input that I can use in my app

**Screenshots**
Nothing to see here

**Environment:**
 - Operating System: iOS 14.4
 - Python version: 3.8
 - Software versions:
      -  beeware==0.3.0

**Additional context**

Stacktrace:
```
Traceback (most recent call last):
  File "/Users/marco/Library/Developer/CoreSimulator/Devices/4F7BCA2A-FCE6-4B17-83DA-1CA6B934C240/data/Containers/Bundle/Application/9A9CCD91-15F9-4533-9C01-65FBBBE32BB8/.app/Library/Application Support/dev.covaxx.findvaccinations/app_packages/rubicon/objc/api.py", line 262, in __call__
    result = self.py_method(py_self, *args)
  File "/Users/marco/Library/Developer/CoreSimulator/Devices/4F7BCA2A-FCE6-4B17-83DA-1CA6B934C240/data/Containers/Bundle/Application/9A9CCD91-15F9-4533-9C01-65FBBBE32BB8/.app/Library/Application Support/dev.covaxx.findvaccinations/app_packages/toga_iOS/app.py", line 46, in application_didFinishLaunchingWithOptions_
    App.app.create()
  File "/Users/marco/Library/Developer/CoreSimulator/Devices/4F7BCA2A-FCE6-4B17-83DA-1CA6B934C240/data/Containers/Bundle/Application/9A9CCD91-15F9-4533-9C01-65FBBBE32BB8/.app/Library/Application Support/dev.covaxx.findvaccinations/app_packages/toga_iOS/app.py", line 105, in create
    self.interface.startup()
  File "/Users/marco/Library/Developer/CoreSimulator/Devices/4F7BCA2A-FCE6-4B17-83DA-1CA6B934C240/data/Containers/Bundle/Application/9A9CCD91-15F9-4533-9C01-65FBBBE32BB8/.app/Library/Application Support/dev.covaxx.findvaccinations/app/findvaccinations/app.py", line 59, in startup
    textbox = toga.MultilineTextInput(id='view1')
  File "/Users/marco/Library/Developer/CoreSimulator/Devices/4F7BCA2A-FCE6-4B17-83DA-1CA6B934C240/data/Containers/Bundle/Application/9A9CCD91-15F9-4533-9C01-65FBBBE32BB8/.app/Library/Application Support/dev.covaxx.findvaccinations/app_packages/toga/widgets/multilinetextinput.py", line 31, in __init__
    self.value = initial
  File "/Users/marco/Library/Developer/CoreSimulator/Devices/4F7BCA2A-FCE6-4B17-83DA-1CA6B934C240/data/Containers/Bundle/Application/9A9CCD91-15F9-4533-9C01-65FBBBE32BB8/.app/Library/Application Support/dev.covaxx.findvaccinations/app_packages/toga/widgets/multilinetextinput.py", line 76, in value
    self._impl.set_value(cleaned_value)
  File "/Users/marco/Library/Developer/CoreSimulator/Devices/4F7BCA2A-FCE6-4B17-83DA-1CA6B934C240/data/Containers/Bundle/Application/9A9CCD91-15F9-4533-9C01-65FBBBE32BB8/.app/Library/Application Support/dev.covaxx.findvaccinations/app_packages/toga_iOS/widgets/multilinetextinput.py", line 118, in set_value
    self.native.text = self.interface._value
AttributeError: 'MultilineTextInput' object has no attribute '_value'
```

**Comment by freakboy3742** [comment]
Fixed in #1440.
