### ISSUE TITLE
Can't insert widgets to boxes on Android

### ISSUE THREAD

**Issue by CarterSnich** [beeware/toga#1239]
**Describe the bug**
Errors (inserted below) are produced when inserting a widget to a box on Android.

**To Reproduce**
1. Insert a new widget dynamically, like by doing `box.insert(toga.Label(text="Hello, World!"))`
2. Check the Android logs by running `adb.exe logcat -s MainActivity:* stdio:* Python:*`

**Expected behavior**
A new widget should be added dynamically.

**Environment:**
 - Operating System: Windows 10 Pro
 - Python version: 3.7.6 64-bit
 - Software versions:
   - Briefcase: `0.3.5`
   - Toga: `toga-core 0.3.0.dev26`

**Additional context**
- Below is the `adb` log
```
04-03 19:37:45.231 32307 32307 D Python  : Native invocation 506708658384 :: onClick
04-03 19:37:45.267 32307 32307 I Python  : [Android] Not implemented: Button.set_background_color()
04-03 19:37:45.269 32307 32307 I Python  : [Android] Not implemented: Widget.set_hidden()
04-03 19:37:45.301 32307 32307 E Python  : Traceback (most recent call last):
04-03 19:37:45.302 32307 32307 E Python  :   File "/data/user/0/darkwarecorps.com.helloworld/files/python/user_code/app_packages/rubicon/java/api.py", line 45, in dispatch
04-03 19:37:45.302 32307 32307 E Python  :     val = getattr(pyinstance, method)(*args)
04-03 19:37:45.302 32307 32307 E Python  :   File "/data/user/0/darkwarecorps.com.helloworld/files/python/user_code/app_packages/toga_android/widgets/button.py", line 14, in onClick
04-03 19:37:45.302 32307 32307 E Python  :     self.button_impl.interface.on_press(widget=self.button_impl.interface)
04-03 19:37:45.302 32307 32307 E Python  :   File "/data/user/0/darkwarecorps.com.helloworld/files/python/user_code/app_packages/toga/handlers.py", line 55, in _handler
04-03 19:37:45.302 32307 32307 E Python  :     result = handler(interface, *args, **kwargs)
04-03 19:37:45.303 32307 32307 E Python  :   File "/data/user/0/darkwarecorps.com.helloworld/files/python/user_code/app/helloworld/app.py", line 48, in launch_code
04-03 19:37:45.303 32307 32307 E Python  :     self.aftermath.insert(self.aftermath_index, toga.Button(label="{} : {}".format(self.aftermath_index, self.codes_input.value)))
04-03 19:37:45.303 32307 32307 E Python  :   File "/data/user/0/darkwarecorps.com.helloworld/files/python/user_code/app_packages/toga/widgets/base.py", line 112, in insert
04-03 19:37:45.303 32307 32307 E Python  :     self._impl.insert_child(index, child._impl)
04-03 19:37:45.303 32307 32307 E Python  : AttributeError: 'Box' object has no attribute 'insert_child'
04-03 19:37:45.303 32307 32307 D Python  : Native invocation done.
```

- Partial code
```
class HellWorld(toga.App):

    aftermath_index = 0

    def startup(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))

        # top label
        label = toga.Label(
            'Enter your nuclear codes:',
            style=Pack(flex=1)
        )
    
        # code box
        codes_box = toga.Box(style=Pack(direction=ROW))
        self.codes_input = toga.TextInput()
        codes_box.add(self.codes_input)

        button_box = toga.Box(style=Pack(direction=ROW))
        button = toga.Button(label="Launch nuke!", on_press=self.launch_code)
        button_box.add(button)

        self.aftermath = toga.Box(style=Pack(direction=ROW))

        self.aftermath.insert(0, toga.Label(
            text="asdads"
        ))

        main_box.add(label)
        main_box.add(codes_box)
        main_box.add(button_box)
        main_box.add(self.aftermath)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

    def launch_code(self, widget):
        self.aftermath.insert(self.aftermath_index, toga.Button(label="{} : {}".format(self.aftermath_index, self.codes_input.value)))
        self.aftermath_index += 1
```

**Comment by freakboy3742** [comment]
I believe this has now been fixed.
