### ISSUE TITLE
Support for .NetFramework 4.0

### ISSUE THREAD

**Issue by chenyulue** [beeware/toga#1327]
I build the example app `helloworld` according to the tutorial in my win7 os, and I get the following error:

```shell
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\pypoetry\cache\virtualenvs\beeware-tutorial-ddkd1cft-py3.8\lib\site-packages\toga_winforms\app.py", line 199, in run_app
    self.loop.run_forever(self.app_context)
  File "c:\users\administrator\appdata\local\pypoetry\cache\virtualenvs\beeware-tutorial-ddkd1cft-py3.8\lib\site-packages\toga_winforms\libs\proactor.py", line 96, in run_forever
    self.enqueue_tick()
  File "c:\users\administrator\appdata\local\pypoetry\cache\virtualenvs\beeware-tutorial-ddkd1cft-py3.8\lib\site-packages\toga_winforms\libs\proactor.py", line 104, in enqueue_tick
    Task.Delay(5).ContinueWith(self.task)
AttributeError: type object 'Task' has no attribute 'Delay'
```

Since in my win7, only .NetFramework 4.0 can be installed, while `Task.Delay` is a new feature of .NetFramework 4.5, the example app can not run. 

In .NetFramework 4.0, the namespace `System.Threading.Tasks` gives the `Task` object which doesn't have the method `Delay`. 

So any idea to support .NetFramework 4.0?

The simplest solution is to just install .NetFramework 4.5, but I don't have any authority to install the .netframework in my working computer, where only .NetFramework 4.0 is installed.

**Comment by freakboy3742** [comment]
Microsoft's EOL date for Windows 7 was Jan 14 2020; at this point, it is an unsupported operating system.

If someone were to contribute a patch with low maintenance overhead that enabled support for .Net Framework 4 (e.g., replacing `.Delay()` with an equivalent method that exists in .Net Framework 4), I wouldn't reject it; but developing support for an operating system that isn't maintained by it's developer isn't going to be high on our list of priorities.
