### ISSUE TITLE
Can't run one of the examples in the doc tutorial on windows, cannot import name 'LEFT'

### ISSUE THREAD

**Issue by aarmn** [beeware/toga#1441]
**Describe the bug**
I cant run one of the examples in the doc tutorial on windows (Tutorial 2 - you put the box inside another box…)

**To Reproduce**
copy 3rd tutorial code to a project
install last dev version of toga (major version 2 don't work on windows at all)
run the example code

**Expected behavior**
running without issue

**Log**
`ImportError: cannot import name 'LEFT' from 'toga_winforms.libs' `

**Environment:**
 - Operating System: windows
 - Python version: 3.9
 - Toga version: 0.3.0.dev28

**Comment by freakboy3742** [comment]
I can't reproduce this error. I strongly suspect that you've got an install of Toga 0.2 (or part of an install of toga 0.2 - for example, toga-core 0.2, but toga-winforms 0.3.0dev28).

If you're still having this problem, please provide a full stack trace (not just the final error), as well as a dump of `pip freeze`.

**Comment by aarmn** [comment]
Ensured both pip and python running are on same version
No modification on installed python packages took place
I had some issues with pythonnet before.

As far as I see all are on last version

pip freeze output
```
aiohttp==3.7.4.post0
antlr4-python3-runtime==4.9.2
anyio==3.1.0
arabic-reshaper==2.1.3
argon2-cffi==20.1.0
art==5.3
astroid==2.5.6
asttokens==2.0.5
async-generator==1.10
async-timeout==3.0.1
attrs==21.2.0
autobahn==21.3.1
autopep8==1.5.6
backcall==0.2.0
bidict==0.21.2
bleach==3.3.0
blessings==1.7
boltons==21.0.0
bpython==0.21
CacheControl==0.12.10
cachy==0.3.0
certifi==2021.10.8
cffi==1.14.5
chardet==4.0.0
charset-normalizer==2.0.12
cheap-repr==0.4.5
Ciphey==3.0.5
cleo==0.8.1
click==8.0.3
clikit==0.6.2
colorama==0.4.4
colorful==0.5.4
colosseum==0.2.0
crashtest==0.3.1
cryptography==3.4.7
curses @ file:///C:/Users/aarmn/Downloads/curses-2.2.1%2Butf8-cp39-cp39-win_amd64.whl
curtsies==0.3.5
cwcwidth==0.1.4
decorator==5.0.7
defusedxml==0.7.1
Deprecated==1.2.12
distlib==0.3.4
dnspython==2.1.0
docutils==0.17
entrypoints==0.3
envelope==1.5.2
executing==0.6.0
filelock==3.6.0
fire==0.4.0
Flask==2.0.2
future==0.18.2
geckodriver-autoinstaller==0.1.0
greenlet==1.1.0
hjson==3.0.2
html5lib==1.1
hyperlink==21.0.0
idna==3.3
importlib-metadata==4.11.3
inflection==0.5.1
inquirerpy==0.3.3
ipykernel==5.5.5
ipython==7.22.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
isort==5.8.0
itsdangerous==2.0.1
jedi==0.18.0
Jinja2==3.0.3
jsoncodable==0.1.7
jsonpickle==2.0.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyter-server==1.8.0
jupyter-server-proxy==3.0.2
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
k-selenium-cookies==0.0.4
keyring==23.5.0
Kivy==2.0.0
kivy-deps.angle==0.3.0
kivy-deps.glew==0.3.0
kivy-deps.sdl2==0.3.1
Kivy-Garden==0.1.4
kivymd==0.1.2
kproxy==0.0.1
lazy-object-proxy==1.6.0
libmagic==1.0
llvmlite==0.37.0
lockfile==0.12.2
lolcat==1.4
MarkupSafe==2.0.1
mccabe==0.6.1
memcache==0.8.0
mistune==0.8.4
MouseInfo==0.1.3
mpmath==1.2.1
msgpack==1.0.3
multidict==5.1.0
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
noraise==0.0.16
not-very-useful-animal==0.1.0
notebook==6.4.0
npyscreen==4.10.5
Nuitka==0.6.14.4
Nuitka64==6.1.151
numba==0.54.1
numpy==1.20.3
orjson==3.5.1
packaging==20.9
pandocfilters==1.4.3
parso==0.8.2
pastel==0.2.1
pexpect==4.8.0
pfzy==0.3.4
pickleshare==0.7.5
pkginfo==1.8.2
platformdirs==2.5.1
poetry==1.1.13
poetry-core==1.0.8
prettyqt==0.183.2
prometheus-client==0.11.0
prompt-toolkit==3.0.18
ptyprocess==0.7.0
py3-validate-email==1.0.0
PyAutoGUI==0.9.53
pycodestyle==2.7.0
pycparser==2.21
pydub==0.25.1
PyGetWindow==0.0.9
Pygments==2.8.1
pyjion==0.15.0
pylev==1.4.0
pylint==2.8.2
PyMsgBox==1.0.9
pyparsing==3.0.7
pyperclip==1.8.2
pypiwin32==223
PyRect==0.1.4
pyrsistent==0.17.3
PyScreeze==0.1.28
pyside-material==1.17
PySide2==5.15.2
PySide6==6.0.3
PySimpleGUI==4.39.1
pytenet==0.0.2
python-bidi==0.4.2
python-dateutil==2.8.1
python-gnupg==0.4.7
python-magic==0.4.24
python-magic-bin==0.4.14
pythondialog==3.5.1
pythonnet==2.5.2
pytube==11.0.1
pytweening==1.0.4
pywin32==300
pywin32-ctypes==0.2.0
pywinpty==1.1.2
pyxdg==0.27
PyYAML==6.0
pyzmq==19.0.2
qsharp==0.17.2105.144881
qsharp-chemistry==0.17.2105.144881
qsharp-core==0.17.2105.144881
qstylizer==0.1.10
qt-material==2.8.4
qtconsole==5.1.0
QtPy==1.9.0
questionary==1.10.0
readme-renderer==29.0
regex==2020.11.13
requests==2.27.1
requests-file==1.5.1
requests-toolbelt==0.9.1
rfc3986==1.5.0
rope==0.19.0
selenium==3.141.0
selenium-browser==0.0.11
selenium-firefox==2.0.4
Send2Trash==1.5.0
shellingham==1.4.0
shiboken2==5.15.2
shiboken6==6.0.3
simpervisor==0.4
six==1.16.0
sniffio==1.2.0
snoop==0.3.0
sympy==1.9
termcolor==1.1.0
terminado==0.10.1
testpath==0.5.0
tinycss==0.4
tldextract==3.1.0
toga==0.3.0.dev28
toga-core==0.3.0.dev28
toga-winforms==0.3.0.dev28
toml==0.10.2
tomlkit==0.10.0
tornado==6.1
tqdm==4.60.0
traitlets==5.0.5
travertino==0.1.3
twine==3.4.1
txaio==21.2.1
typing-extensions==3.10.0.0
urllib3==1.26.9
virtualenv==20.13.4
vpython==7.6.1
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.1.0
Werkzeug==2.0.2
widgetsnbextension==3.5.1
wrapt==1.12.1
xpath-utils==0.0.2
yarl==1.6.3
zipp==3.7.0
```

full error log
```
Traceback (most recent call last):
  File "Path to my python file", line 163, in <module>
    main().main_loop()
  File "Path to my python file", line 159, in main
    return toga.App('First App', 'org.beeware.helloworld', startup=build)
  File "C:\Program Files\Python39\lib\site-packages\toga\app.py", line 54, in __init__
    self.factory = get_platform_factory(factory)
  File "C:\Program Files\Python39\lib\site-packages\toga\platform.py", line 42, in get_platform_factory
    from toga_winforms import factory
  File "C:\Program Files\Python39\lib\site-packages\toga_winforms\factory.py", line 14, in <module>
    from .widgets.numberinput import NumberInput
  File "C:\Program Files\Python39\lib\site-packages\toga_winforms\widgets\numberinput.py", line 1, in <module>
    from toga_winforms.libs import LEFT, RIGHT, CENTER
ImportError: cannot import name 'LEFT' from 'toga_winforms.libs' (C:\Program Files\Python39\lib\site-packages\toga_winforms\libs\__init__.py)
```

**Comment by freakboy3742** [comment]
As I suspected, there's an environment configuration issue going on here. 

Your pip install says you've got toga 0.3.0.dev28 installed. That is a red flag on it's own, because the current dev version of Toga is 0.3.0dev32 - so I don't know how you've installed a year-old development version if you're following the tutorial (which advises you to run `pip install --pre toga`)

Then, your stack trace says Line 1 of `toga_winforms/widgets/numberinput.py` is `from toga_winforms.libs import LEFT, RIGHT, CENTER`. However, [that isn't the contents of the file as of 0.3.0.dev28](https://github.com/beeware/toga/blob/v0.3.0.dev28/src/winforms/toga_winforms/widgets/numberinput.py). You have to go back to [toga 0.3.0.dev8](https://github.com/beeware/toga/blob/v0.3.0.dev8/src/winforms/toga_winforms/widgets/numberinput.py) to have that content in `numberinput.py`.

So - the version of Python that is running your app is not the same as the version of Python that was running `pip`. You have at least 2 Python environment on this machine, and they have different versions of Toga installed.

Based on the paths in your stack trace, it appears that you're *not* using a virtual environment (or, at the very least, it's not active) - my first recommendation would be to follow the recommendations of the tutorial, and use (and activate) a virtual environment when running the tutorial.

My second recommendation is to invoke `python -m pip`, rather than `pip`. This is [especially important on Windows because of how Windows manages paths](https://snarky.ca/why-you-should-use-python-m-pip/). It appears that our tutorial doesn't currently include this recommendation, which is an oversight on our part; I've just made that change (#1446).
