### ISSUE TITLE
Core tests fail on Windows due to capitalisation issue with paths

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#1567]
### Discussed in https://github.com/beeware/toga/discussions/1566

<div type='discussions-op-text'>

<sup>Originally posted by **gregcowell** August 22, 2022</sup>
I have just setup my development environment. When I run the core test suite I am getting 8 failures.  I have omitted the successful test output below. The only thing I have done differently to the instructions is call my virtual environment directory "toga" instead of "venv".  I am using Python 3.10.5 on Windows 11.
```
(toga) PS C:\Users\gregc\python\toga\toga\src\core> python setup.py test

======================================================================
FAIL: test_as_file (tests.test_paths.TestPaths)
When started as `python app.py`, the app path is the folder holding app.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 90, in test_as_file
    self.assert_standalone_paths(output)
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 67, in assert_standalone_paths
    self.assertIn(
AssertionError: 'app.paths.toga=c:\\users\\gregc\\python\\toga\\toga\\src\\core\\toga' not found in ['app.paths.app=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\tests\\testbed', 'app.paths.data=C:\\Users\\gregc\\user_data\\org.testbed.standalone-app', 'app.paths.cache=C:\\Users\\gregc\\cache\\org.testbed.standalone-app', 'app.paths.logs=C:\\Users\\gregc\\logs\\org.testbed.standalone-app', 'app.paths.toga=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\toga']

======================================================================
FAIL: test_as_interactive (tests.test_paths.TestPaths)
At an interactive prompt, the app path is the current working directory
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 80, in test_as_interactive
    self.assert_standalone_paths(output)
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 67, in assert_standalone_paths
    self.assertIn(
AssertionError: 'app.paths.toga=c:\\users\\gregc\\python\\toga\\toga\\src\\core\\toga' not found in ['app.paths.app=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\tests\\testbed', 'app.paths.data=C:\\Users\\gregc\\user_data\\org.testbed.standalone-app', 'app.paths.cache=C:\\Users\\gregc\\cache\\org.testbed.standalone-app', 'app.paths.logs=C:\\Users\\gregc\\logs\\org.testbed.standalone-app', 'app.paths.toga=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\toga']

======================================================================
FAIL: test_as_module (tests.test_paths.TestPaths)
When started as `python -m app`, the app path is the folder holding app.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 100, in test_as_module
    self.assert_standalone_paths(output)
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 67, in assert_standalone_paths
    self.assertIn(
AssertionError: 'app.paths.toga=c:\\users\\gregc\\python\\toga\\toga\\src\\core\\toga' not found in ['app.paths.app=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\tests\\testbed', 'app.paths.data=C:\\Users\\gregc\\user_data\\org.testbed.standalone-app', 'app.paths.cache=C:\\Users\\gregc\\cache\\org.testbed.standalone-app', 'app.paths.logs=C:\\Users\\gregc\\logs\\org.testbed.standalone-app', 'app.paths.toga=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\toga']

======================================================================
FAIL: test_installed_as_module (tests.test_paths.TestPaths)
When the installed app is started, the app path is the folder holding app.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 193, in test_installed_as_module
    self.assertIn(f"app.paths.toga={Path(toga.__file__).parent}", results)
AssertionError: 'app.paths.toga=c:\\users\\gregc\\python\\toga\\toga\\src\\core\\toga' not found in ['app.paths.app=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\tests\\testbed\\installed', 'app.paths.data=C:\\Users\\gregc\\user_data\\org.testbed.installed', 'app.paths.cache=C:\\Users\\gregc\\cache\\org.testbed.installed', 'app.paths.logs=C:\\Users\\gregc\\logs\\org.testbed.installed', 'app.paths.toga=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\toga']

======================================================================
FAIL: test_simple_as_deep_file (tests.test_paths.TestPaths)
When a simple app is started as `python simple/app.py`, the app path is the folder holding app.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 155, in test_simple_as_deep_file
    self.assert_simple_paths(output)
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 120, in assert_simple_paths
    self.assertIn(
AssertionError: 'app.paths.toga=c:\\users\\gregc\\python\\toga\\toga\\src\\core\\toga' not found in ['app.paths.app=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\tests\\testbed\\simple', 'app.paths.data=C:\\Users\\gregc\\user_data\\org.testbed.simple-app', 'app.paths.cache=C:\\Users\\gregc\\cache\\org.testbed.simple-app', 'app.paths.logs=C:\\Users\\gregc\\logs\\org.testbed.simple-app', 'app.paths.toga=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\toga']

======================================================================
FAIL: test_simple_as_deep_module (tests.test_paths.TestPaths)
When a simple app is started as `python -m simple`, the app path is the folder holding app.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 165, in test_simple_as_deep_module
    self.assert_simple_paths(output)
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 120, in assert_simple_paths
    self.assertIn(
AssertionError: 'app.paths.toga=c:\\users\\gregc\\python\\toga\\toga\\src\\core\\toga' not found in ['app.paths.app=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\tests\\testbed\\simple', 'app.paths.data=C:\\Users\\gregc\\user_data\\org.testbed.simple-app', 'app.paths.cache=C:\\Users\\gregc\\cache\\org.testbed.simple-app', 'app.paths.logs=C:\\Users\\gregc\\logs\\org.testbed.simple-app', 'app.paths.toga=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\toga']

======================================================================
FAIL: test_simple_as_file_in_module (tests.test_paths.TestPaths)
When a simple app is started as `python app.py` inside a runnable module,
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 134, in test_simple_as_file_in_module
    self.assert_simple_paths(output)
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 120, in assert_simple_paths
    self.assertIn(
AssertionError: 'app.paths.toga=c:\\users\\gregc\\python\\toga\\toga\\src\\core\\toga' not found in ['app.paths.app=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\tests\\testbed\\simple', 'app.paths.data=C:\\Users\\gregc\\user_data\\org.testbed.simple-app', 'app.paths.cache=C:\\Users\\gregc\\cache\\org.testbed.simple-app', 'app.paths.logs=C:\\Users\\gregc\\logs\\org.testbed.simple-app', 'app.paths.toga=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\toga']

======================================================================
FAIL: test_simple_as_module (tests.test_paths.TestPaths)
When a simple apps is started as `python -m app` inside a runnable module,
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 145, in test_simple_as_module
    self.assert_simple_paths(output)
  File "c:\users\gregc\python\toga\toga\src\core\tests\test_paths.py", line 120, in assert_simple_paths
    self.assertIn(
AssertionError: 'app.paths.toga=c:\\users\\gregc\\python\\toga\\toga\\src\\core\\toga' not found in ['app.paths.app=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\tests\\testbed\\simple', 'app.paths.data=C:\\Users\\gregc\\user_data\\org.testbed.simple-app', 'app.paths.cache=C:\\Users\\gregc\\cache\\org.testbed.simple-app', 'app.paths.logs=C:\\Users\\gregc\\logs\\org.testbed.simple-app', 'app.paths.toga=C:\\Users\\gregc\\python\\toga\\toga\\src\\core\\toga']

----------------------------------------------------------------------
Ran 503 tests in 1.815s

FAILED (failures=8, skipped=1)
Test failed: <unittest.runner.TextTestResult run=503 errors=0 failures=8>
error: Test failed: <unittest.runner.TextTestResult run=503 errors=0 failures=8>
```</div>

**Comment by gregcowell** [comment]
I am working on a pull request for this.
