### ISSUE TITLE
Unable to start app

### ISSUE THREAD

**Issue by annetracy** [beeware/toga#1613]
My rotate_video app runs successfully in dev mode (briefcase dev), 
it builds successfully (briefcase build), but fails to run (briefcase run)

I get the following message(s) I'm not even sure this is a Toga issue.

> [rotate_video] Built linux/Rotate_Video-0.0.1-x86_64.AppImage
(rotate_video-venv) tracy@daphne:~/Projects/RotateVideos/rotate_video$ briefcase run

[rotate_video] Starting app...

** (process:72473): WARNING **: 19:04:21.337: Failed to load shared library 'libpango-1.0.so.0' referenced by the typelib: /usr/lib/libpango-1.0.so.0: undefined symbol: g_memdup2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/.mount_RotatecyrrfT/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/tmp/.mount_RotatecyrrfT/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/tmp/.mount_RotatecyrrfT/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_RotatecyrrfT/usr/app/rotate_video/__main__.py", line 4, in <module>
    main().main_loop()
  File "/tmp/.mount_RotatecyrrfT/usr/app/rotate_video/app.py", line 386, in main
    return Rotate_Video()
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/toga/app.py", line 278, in __init__
    self.factory = get_platform_factory(factory)
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/toga/platform.py", line 41, in get_platform_factory
    from toga_gtk import factory
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/toga_gtk/factory.py", line 1, in <module>
    from .app import App, DocumentApp, MainWindow
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/toga_gtk/app.py", line 13, in <module>
    from .keys import gtk_accel
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/toga_gtk/keys.py", line 3, in <module>
    from .libs import Gdk
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/toga_gtk/libs/__init__.py", line 1, in <module>
    from .gtk import *  # noqa: F401, F403
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/toga_gtk/libs/gtk.py", line 5, in <module>
    from gi.repository import Gtk, Gdk, GdkPixbuf, Gio, GLib, GObject  # noqa: F401, E402
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_RotatecyrrfT/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_RotatecyrrfT/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/gi/importer.py", line 150, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/tmp/.mount_RotatecyrrfT/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/gi/overrides/Pango.py", line 41, in <module>
    FontDescription = override(FontDescription)
  File "/tmp/.mount_RotatecyrrfT/usr/app_packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError

Operating System: Manjaro Linux
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.15.72-1-MANJARO (64-bit)
Graphics Platform: X11

GTK2  V2.24.33
GTK3 V3.24.34

**Comment by annetracy** [comment]
This

`linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]
`
was missing from the toml file.

I added those 3 lines, ran briefcase creat, briefcase build, and briefcase run, and the app ran successfully, but with the following errors.

`video$ briefcase run

[rotate_video] Starting app...
Gtk-Message: 22:08:41.882: Failed to load module "xapp-gtk3-module"
Gtk-Message: 22:08:41.904: Failed to load module "canberra-gtk-module"
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
Gtk-Message: 22:08:42.703: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 22:08:42.719: Failed to load module "colorreload-gtk-module"
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so

`

As a consequence the system Appearance Settings were ignored.

**Comment by annetracy** [comment]
I'll get onto that as soon as I recover from building our raised Gardens.

**Comment by annetracy** [comment]
Warning: This message has had one or more attachments removed
Warning: (briefcase.2022_10_13-15_17_39.run.log).
Warning: Please read the "INFOTECHWEB-Attachment-Warning.txt" attachment(s) for more information.



Here's the Log

Sent from Claws Mail on my Manjaro Linux Computer, where Free means Freedom,
and Privacy is.

On Wed, 12 Oct 2022 03:14:31 -0700
Russell Keith-Magee ***@***.***> wrote:

> briefcase run --log

This is a message from the MailScanner E-Mail Virus Protection Service
----------------------------------------------------------------------
The original e-mail attachment "briefcase.2022_10_13-15_17_39.run.log"
is on the list of unacceptable attachments for this site and has been
replaced by this warning message.

If you wish to receive a copy of the original attachment, please
e-mail helpdesk and include the whole of this message
in your request. Alternatively, you can call them, with
the contents of this message to hand when you call.

At Thu Oct 13 15:21:39 2022 the virus scanner said:
   MailScanner: Attempt to hide real filename extension (briefcase.2022_10_13-15_17_39.run.log)

Note to Help Desk: Look on The INFOTECHWEB () MailScanner in /var/spool/MailScanner/quarantine/20221013 (message 1oiqeU-00009W-J1).
-- 
Postmaster
INFO TECH WEB
https://hostingoz.net/manage/terms-of-service.php

**Comment by annetracy** [comment]
Log emailed to return address.

**Comment by freakboy3742** [comment]
The log has been stripped by a virus checker,. You can upload it directly by dragging it into a comment window on Github.

**Comment by annetracy** [comment]
How do I get the file to you?

When copy paste it's content it's too long.

When Attempt upload it I get 'Something went really wrong, and we can't process that file. Try again'

When I email it to you, I I get the above 'Warning: This message has had one or more attachments removed'

**Comment by freakboy3742** [comment]
Like I said in my last comment - drag it into the comment box in Github. It will be uploaded as an attachment to your comment.

**Comment by annetracy** [comment]
The file name ends with .run.log, the virus checker appears to believe this is an attempt to hide the real file extension. I've changed the name to end in _run.log, and will retry emailing it.

**Comment by annetracy** [comment]
Tray again.

Sent from Claws Mail on my Manjaro Linux Computer, where Free means Freedom,
and Privacy is.

**Comment by freakboy3742** [comment]
[briefcase.2022_10_13-14_09_45.update.log](https://github.com/beeware/toga/files/9771302/briefcase.2022_10_13-14_09_45.update.log)

**Comment by freakboy3742** [comment]
Your email client is thing being "smart" here. Don't use it. Drag and drop the file from your file manager into the text box that you use to add a comment to this thread, and you'll get something that looks like this:
[briefcase.2022_10_13-14_09_45.update.log](https://github.com/beeware/toga/files/9771315/briefcase.2022_10_13-14_09_45.update.log)

**Comment by annetracy** [comment]
Unless you received the file as an attachment in an email, I'm still getting the message..

'Something went really wrong, and we can't process that file. Try again'

When I attenpt to upload it via this comment system.

**Comment by annetracy** [comment]
Dragging and dropping the file, clicking on the bottom section of the editor and navigating to the file, makes no difference, I get the message..

'Something went really wrong, and we can't process that file. Try again'

**Comment by freakboy3742** [comment]
Sounds like your browser might be "helping" with some virus checking of its own.

My next suggestion would be to zip the log file, and upload the zipped version. That's sometimes enough to convince virus checkers they don't need to panic.

**Comment by annetracy** [comment]
Same error message, with Zipped File... and with pdf. The file is quite large, would that be a problem?

**Comment by freakboy3742** [comment]
Depends on what you mean by "Quite large". PDF won't make the document much smaller, but zipping it should - it's text content. How big is the raw and zip versions?

**Comment by annetracy** [comment]
the zip is only 20K, (the raw 383K), so I think size isn't the problem.

Try this https://www.mediafire.com/file/he5o4xvhdjij2f0/briefcase.2022_10_13-15_17_39_run.zip/file
