### ISSUE TITLE
False positive "Multiple candidiate toga backends"

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#1636]
**Describe the bug**
When using a development version of *toga*, a `RuntimeError` of multiple candidate toga backends is raised with the same backend. Stacktrace example:

```
Traceback (most recent call last):
  File "C:\Users\sagi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sagi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\sagi\PycharmProjects\toga\examples\canvas\canvas\__main__.py", line 4, in <module>
    main().main_loop()
  File "C:\Users\sagi\PycharmProjects\toga\examples\canvas\canvas\app.py", line 565, in main
    return ExampleCanvasApp('Canvas', 'org.beeware.widgets.canvas')
  File "C:\Users\sagi\PycharmProjects\toga\src\core\src\toga\app.py", line 308, in __init__
    self.factory = get_platform_factory()
  File "C:\Users\sagi\PycharmProjects\toga\src\core\src\toga\platform.py", line 106, in get_platform_factory
    raise RuntimeError(
RuntimeError: Multiple candidiate toga backends found: ('toga_winforms' (windows), 'toga_winforms' (windows)). Uninstall the backends you don't require, or use TOGA_BACKEND to specify a backend.
```

**To Reproduce**
1. Open a new virtual environment
2. Go to src\core
3. Run `pip install -e .`
4. Go to src\winforms
5. Run `pip install -e .`
6. Go to example\canvas (or any other example application)
7. Run `python -m canvas`

**Expected behavior**
`RuntimeError` should not be raised in that case.

**Environment:**
 - Operating System: Windows
 - Python version: 3.10.6
 - Software versions:
   - Briefcase: latest
   - Toga: latest

**Comment by freakboy3742** [comment]
Darn... I'm seeing this on a fresh install too. If you manually delete the .egg-info file in the backend folder, or delete the pyproject.toml file, the problem goes away. Not sure what the permanent fix is.
