### ISSUE TITLE
`add_background_task` is not thread-safe, causes crashes in dev mode

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#1705]
`add_background_thread` is the only public Toga API which allows background threads to schedule things on the main thread, and we've [previously recommended](https://github.com/beeware/toga/discussions/1538#discussioncomment-3285587) people to use it for that purpose.

All 5 backends have identical implementations of this method:
```
    def add_background_task(self, handler):
        self.loop.call_soon(handler, self)
```

However, `call_soon` is not guaranteed to be thread-safe. This causes a crash on Windows when running the testbed app in `briefcase dev`, which enables extra debug checks:
```
Traceback (most recent call last):
  File "C:\Users\smith\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\smith\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\smith\cygwin\git\beeware\toga\testbed\tests\testbed.py", line 43, in run_tests
    app.add_background_task(lambda app, **kwargs: app.exit())
  File "C:\Users\smith\cygwin\.venv\bw-test\lib\site-packages\toga\app.py", line 595, in add_background_task
    self._impl.add_background_task(wrapped_handler(self, handler))
  File "C:\Users\smith\cygwin\.venv\bw-test\lib\site-packages\toga_winforms\app.py", line 308, in add_background_task
    self.loop.call_soon(handler, self)
  File "C:\Users\smith\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 721, in call_soon
    self._check_thread()
  File "C:\Users\smith\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 758, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
```

Instead, we should use `call_soon_threadsafe`. And since we're using custom event loops, we should also check whether their implementations of `call_soon_threadsafe` actually are thread-safe, and fix them if not.

To avoid having 5 identical implementations, maybe we could merge them into interface layer, relying on the fact that every backend has a `loop` property.

**Comment by freakboy3742** [comment]
Agreed. I have a vague recollection that one of the earlier implementations was very slightly platform dependent; however, based on the current state of things, I can't see any reason why it shouldn't be consolidated into the interface layer. Using `call_soon_threadsafe()` also seems like a good idea to me.

Based on my spelunking with gbulb and Rubicon yesterday, I *think* the `call_soon_threadsafe()` methods are, in fact, thread safe; they're both implemented as "post a message to the event loop" APIs, which means that no matter which thread they're called from, they should be executed on the main thread.
