### ISSUE TITLE
Passing an empty argument to Cocoa app produces AttributeError

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#1774]
```
% briefcase run -- "" 
...
Exception ignored on calling ctypes callback function: <rubicon.objc.api.objc_method object at 0x10e2fa250>
Traceback (most recent call last):
  File "/Users/msmith/git/beeware/apps/passthrough/macOS/app/passthrough/passthrough.app/Contents/Resources/app_packages/rubicon/objc/api.py", line 333, in __call__
    result = self.py_method(py_self, *args)
  File "/Users/msmith/git/beeware/apps/passthrough/macOS/app/passthrough/passthrough.app/Contents/Resources/app_packages/toga_cocoa/app.py", line 96, in application_openFiles_
    self.impl.open_document(str(fileURL.absoluteString))
AttributeError: 'NoneType' object has no attribute 'absoluteString'
```

It appears to be harmless, and connected to the undocumented `DocumentApp` API.

**Comment by freakboy3742** [comment]
It's a bit of an edge case - in "normal operation", you wouldn't be able to start an app with an empty string as an argument. Still worth catching (and ignoring) the argument, though.

**Comment by mhsmith** [comment]
For future reference: `application_openFiles_` is a method which Cocoa may call at any time, not just during app startup. This was added to allow multiple `open` commands to be handled by the same process, as is the standard behavior on macOS. See Podium for an example.

The GTK backend has a more generic implementation which is based only on `sys.argv`.
