### ISSUE TITLE
Cycle between windows can't find icon resources/window

### ISSUE THREAD

**Issue by eklopfer** [beeware/toga#1895]
### Describe the bug

cd toga/examples/window
> python -m window

After selecting "Create Window" 3 toga windows are created
Moved the main display away from the windows and selected "Cycle between windows"
This resulted in the following traceback:

>python -m window
WARNING: Can't find icon resources/window; falling back to default icon
Error in async handler: 'Form' object has no attribute '_impl'
Traceback (most recent call last):
  File "C:\Users\eilee\beewareToga\toga\core\src\toga\handlers.py", line 28, in handler_with_cleanup
    result = await handler(interface, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eilee\beewareToga\toga\examples\window\window\app.py", line 75, in do_current_window_cycling
    self.label.text = f"Current window is {self.current_window.id}"
                                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eilee\beewareToga\toga\core\src\toga\app.py", line 518, in current_window
    return self._impl.get_current_window().interface
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eilee\beewareToga\toga\winforms\src\toga_winforms\app.py", line 293, in get_current_window
    return WinForms.Form.ActiveForm._impl
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Form' object has no attribute '_impl'

### Steps to reproduce

1. toga/examples/window
2. python -m window
3. Select "Create Window"
4. Move main window away from new windows
5. Select "Cycle between windows"

### Expected behavior

Traceback show above

### Environment

- Operating System: Windows
- Python version: 3.11.3
- Software versions:
  - Briefcase: 
  - Toga: 0.3.2.dev82+gbc44914a
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report. Looks like the Winforms implementation merged in #1887 was buggy. (Ping @proneon267)
