### ISSUE TITLE
Implement DateInput and TimeInput for Cocoa, GTK and iOS

### ISSUE THREAD

**Issue by LunaMeadows** [beeware/toga#1939]
### What is the problem or limitation you are having?

Currently there is no implementation for showing a calendar. It would be useful for at least 2 reasons and probably more. 

1st reason would be allowing the user to select a specific date for the program to use. 
2nd reason would be allowing the program to show a custom calender that the user could fill with their own events that may be useful inside a specific app instead of in the built in calender. An example would be a finance app that allows the user to specify when bills or subscriptions get billed easier.

### Describe the solution you'd like

For Android there is 2 different widgets that can be used for each reason. For displaying a calender with events I *believe* that the [CalenderView](https://developer.android.com/reference/android/widget/CalendarView) is the option that would be wanted. For selecting a date there is a date picker implementation already. 

For Gtk there is only one widget for this. The [Gtk.Calender](https://docs.gtk.org/gtk4/class.Calendar.html) allows for displaying a calendar and has the ability to add custom events as well as the ability to get the selected date. For a date picker implementation a custom window may need to be made similar to the error dialogs and such. 

### Describe alternatives you've considered

Not having a calender widget and having the user manually type in dates and making a custom view for dates and such.

**Comment by freakboy3742** [comment]
DatePicker and TimePicker both exist in the Toga API; however, they're only implemented on Windows and Android. The lack of documentation is definitely an oversight; and we'd definitely like to fill this out with GTK, iOS, Cocoa and Web implementations.

**Comment by LunaMeadows** [comment]
I can see about the GTK implementation. My question there is since a custom widget may need to be made, is there anything with GTK already that would be appropriate to take inspiration from to create it?

Also for web I can look into it as well. If shoelace is still the wanted framework it looks like there has been a [discussion](https://github.com/shoelace-style/shoelace/issues/101) about an implementation of this so I can go from there for an implementation maybe.

**Comment by rmartin16** [comment]
Adding error that happens when you try to use DatePicker on GTK for search seo.

```
Traceback (most recent call last):
  File "/home/russell/github/beeware/toga/examples/date_and_time/build/date_and_time/pop/jammy/date_and_time-0.0.1/usr/lib/date_and_time/app_packages/toga_gtk/app.py", line 98, in gtk_startup
    self.interface.startup()
  File "/home/russell/github/beeware/toga/examples/date_and_time/build/date_and_time/pop/jammy/date_and_time-0.0.1/usr/lib/date_and_time/app/date_and_time/app.py", line 21, in startup
    toga.DatePicker(
  File "/home/russell/github/beeware/toga/examples/date_and_time/build/date_and_time/pop/jammy/date_and_time-0.0.1/usr/lib/date_and_time/app_packages/toga/widgets/datepicker.py", line 43, in __init__
    self._impl = self.factory.DatePicker(interface=self)
AttributeError: module 'toga_gtk.factory' has no attribute 'DatePicker'
```

**Comment by mhsmith** [comment]
This error message will be improved in #1992.

Also, for consistency with the other widgets, DatePicker and TimePicker will be renamed to DateInput and TimeInput in the next version of Toga.

**Comment by johnzhou721** [comment]
PRs that exist:
- #3483
- #3536
- #3574
- [By someone else] #3647

Issues relating to Date and Time Inputs:
- #3580 (non-working fix at #3581)
- #3660 (this request may be terribly mistaken).

Also: #3574 makes macOS the first backend to have all widgets implemented.

**Comment by johnzhou721** [comment]
DateInput for iOS merged! Time to start TimeInput for iOS.

**Comment by johnzhou721** [comment]
TimeInput for iOS started/

**Comment by mhsmith** [comment]
There's no need to post comments on an issue when you start and finish a related PR. Just mention the issue number somewhere in the PR, and GitHub will automatically create a reverse link that indicates the PR status using color, as it has above for #3483.

**Comment by johnzhou721** [comment]
FYI: Comment above for list of PRs edited, iOS users should be aware of the bug.

**Comment by johnzhou721** [comment]
FWIW, I've linked another PR in the list for posterity; all that's left now is TimeInput on GTK+; this is a non-native-existing widget, and 3 GtkSpinButtons might work (h, m, s...)
