### ISSUE TITLE
Setting non-string data in to a `ListSource` on Android does not work

### ISSUE THREAD

**Issue by rmartin16** [beeware/toga#2070]
### Describe the bug

When data that contains non-`string` types is set for a `ListSource` on Android, an indecipherable error is logged.

```
E/g.beeware.tabl: Invalid ID 0x00000001.
W/python.stderr: Error in handler: String resource ID #0x1
W/python.stderr:        at android.content.res.Resources.getText(Resources.java:444)
W/python.stderr:        at android.widget.TextView.setText(TextView.java:6503)
W/python.stderr:        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
W/python.stderr:        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
W/python.stderr:        at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
W/python.stderr:        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
W/python.stderr:        at $Proxy7.onClick(Unknown Source)
W/python.stderr:        at android.view.View.performClick(View.java:7441)
W/python.stderr:        at android.view.View.performClickInternal(View.java:7418)
W/python.stderr:        at android.view.View.access$3700(View.java:835)
W/python.stderr:        at android.view.View$PerformClick.run(View.java:28676)
W/python.stderr:        at android.os.Handler.handleCallback(Handler.java:938)
W/python.stderr:        at android.os.Handler.dispatchMessage(Handler.java:99)
W/python.stderr:        at android.os.Looper.loopOnce(Looper.java:201)
W/python.stderr:        at android.os.Looper.loop(Looper.java:288)
W/python.stderr:        at android.app.ActivityThread.main(ActivityThread.java:7839)
W/python.stderr:        at java.lang.reflect.Method.invoke(Native Method)
W/python.stderr:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/python.stderr:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
W/python.stderr: Traceback (most recent call last):
W/python.stderr:   File "/data/data/org.beeware.table/files/chaquopy/AssetFinder/requirements/toga/handlers.py", line 79, in _handler
W/python.stderr:   File "/data/data/org.beeware.table/files/chaquopy/AssetFinder/app/table/app.py", line 56, in insert_handler
W/python.stderr:   File "/data/data/org.beeware.table/files/chaquopy/AssetFinder/requirements/toga/sources/list_source.py", line 140, in insert
W/python.stderr:   File "/data/data/org.beeware.table/files/chaquopy/AssetFinder/requirements/toga/sources/base.py", line 84, in notify
W/python.stderr:   File "/data/data/org.beeware.table/files/chaquopy/AssetFinder/requirements/toga_android/widgets/table.py", line 196, in insert
W/python.stderr:   File "/data/data/org.beeware.table/files/chaquopy/AssetFinder/requirements/toga_android/widgets/table.py", line 105, in change_source
W/python.stderr:   File "/data/data/org.beeware.table/files/chaquopy/AssetFinder/requirements/toga_android/widgets/table.py", line 158, in create_table_row
W/python.stderr:   File "class.pxi", line 972, in java.chaquopy.JavaMultipleMethod.__get__.lambda3
W/python.stderr:   File "class.pxi", line 1010, in java.chaquopy.JavaMultipleMethod.__call__
W/python.stderr:   File "class.pxi", line 775, in java.chaquopy.JavaMethod.__get__.lambda2
W/python.stderr:   File "class.pxi", line 795, in java.chaquopy.JavaMethod.__call__
W/python.stderr:   File "class.pxi", line 884, in java.chaquopy.JavaMethod.call_nonvirtual_method
W/python.stderr:   File "env.pxi", line 242, in java.chaquopy.CQPEnv.CallNonvirtualVoidMethodA
W/python.stderr:   File "env.pxi", line 546, in java.chaquopy.CQPEnv.check_exception
W/python.stderr: android.content.res.Resources$NotFoundException: String resource ID #0x1
W/python.stderr:        at android.content.res.Resources.getText(Resources.java:444)
W/python.stderr:        at android.widget.TextView.setText(TextView.java:6503)
W/python.stderr:        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
W/python.stderr:        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
W/python.stderr:        at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
W/python.stderr:        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
W/python.stderr:        at $Proxy7.onClick(Unknown Source)
W/python.stderr:        at android.view.View.performClick(View.java:7441)
W/python.stderr:        at android.view.View.performClickInternal(View.java:7418)
W/python.stderr:        at android.view.View.access$3700(View.java:835)
W/python.stderr:        at android.view.View$PerformClick.run(View.java:28676)
W/python.stderr:        at android.os.Handler.handleCallback(Handler.java:938)
W/python.stderr:        at android.os.Handler.dispatchMessage(Handler.java:99)
W/python.stderr:        at android.os.Looper.loopOnce(Looper.java:201)
W/python.stderr:        at android.os.Looper.loop(Looper.java:288)
W/python.stderr:        at android.app.ActivityThread.main(ActivityThread.java:7839)
W/python.stderr:        at java.lang.reflect.Method.invoke(Native Method)
W/python.stderr:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/python.stderr:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Steps to reproduce

Run this app on Android:
```python
import toga


class HelloWorld(toga.App):

    def startup(self):
        """Construct and show the Toga application."""
        table = toga.Table(headings=["column"])
        main_box = toga.Box(children=[table])
        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

        table.data = ("1",)
        table.data = (1,)


def main():
    return HelloWorld()
```

### Expected behavior

The error should be made understandable....or the data should be coerced to `string`. Using an integer in the data on other platforms does not seem to be a problem.

### Environment

- Operating System: pop os 22.04
- Python version: 3.10.12
- Software versions:
  - Briefcase: `0.3.16.dev94+gcd4044e2`
  - Toga: `0.3.2.dev745+g9a482d3a9`

### Logs

[briefcase.2023_08_07-11_18_16.run.log](https://github.com/beeware/toga/files/12281780/briefcase.2023_08_07-11_18_16.run.log)

**Comment by mhsmith** [comment]
This will be because when you call `TextView.setText` with an integer, it looks it up in the app's string resource table. The data should be converted to a string first, so the correct overload is called.

This should be fixed in #2011.
