### ISSUE TITLE
Intermittent testbed failure in Android WebView tests

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#2189]
### Describe the bug

When running CI, the testbed app sometimes raises the following failure on Android when running the `tests/widgets/test_webview.py::test_evaluate_javascript_error_without_handler` test:
```
I/python.stdout: ________________ test_evaluate_javascript_error_without_handler ________________
I/python.stdout: Traceback (most recent call last):
I/python.stdout:   File "stdlib/asyncio/tasks.py", line 650, in _wrap_awaitable
I/python.stdout: asyncio.exceptions.CancelledError
I/python.stdout: 
I/python.stdout: During handling of the above exception, another exception occurred:
I/python.stdout: 
I/python.stdout: Traceback (most recent call last):
I/python.stdout:   File "stdlib/asyncio/tasks.py", line 456, in wait_for
I/python.stdout: asyncio.exceptions.CancelledError
I/python.stdout: 
I/python.stdout: The above exception was the direct cause of the following exception:
I/python.stdout: 
I/python.stdout: Traceback (most recent call last):
I/python.stdout:   File "/data/data/org.beeware.toga.testbed/files/chaquopy/AssetFinder/app/tests/widgets/test_webview.py", line 282, in test_evaluate_javascript_error_without_handler
I/python.stdout:     result = await wait_for(
I/python.stdout:   File "stdlib/asyncio/tasks.py", line 458, in wait_for
I/python.stdout: asyncio.exceptions.TimeoutError
I/python.stdout: ----------------------------- Captured stderr call -----------------------------
I/python.stdout: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected identifier", source: about:blank (1)
```

### Steps to reproduce

Intermittent failure, only seen in CI, and even then, unreliably. 

### Expected behavior

The test should pass reliably.

### Environment

- Operating System: CI
- Python version: 3.10
- Software versions:
  - Briefcase: 0.3.16
  - Toga: 0.4.0

**Comment by freakboy3742** [comment]
We haven't seen this for a while, so it looks like it's been cleared up.
