### ISSUE TITLE
Shows a black screen when launch app

### ISSUE THREAD

**Issue by idbeny** [beeware/toga#2262]
### Describe the bug

Python code
```
"""
Shell written in python
"""
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW


class HelloWorld(toga.App):
    def startup(self):
        main_box = toga.Box(
            style=Pack(direction=COLUMN)
        )

        name_label = toga.Label(
            "HelloWorld",
            style=Pack(padding=(0, 5))
        )
        self.name_input = toga.TextInput(style=Pack(flex=1))

        name_box = toga.Box(
            style=Pack(direction=ROW, padding=5)
        )
        name_box.add(name_label)
        name_box.add(self.name_input)

        main_box.add(name_box)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()


def main():
    return HelloWorld()

```

Log from Xcode
```
2023-12-07 11:39:24.771529+0800 HelloWorld[668:221278] Configuring isolated Python...
2023-12-07 11:39:24.781955+0800 HelloWorld[668:221278] Pre-initializing Python runtime...
2023-12-07 11:39:24.785642+0800 HelloWorld[668:221278] PythonHome: /var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/python-stdlib
2023-12-07 11:39:24.802327+0800 HelloWorld[668:221278] PYTHONPATH:
2023-12-07 11:39:24.802646+0800 HelloWorld[668:221278] - /var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/python-stdlib
2023-12-07 11:39:24.802835+0800 HelloWorld[668:221278] - /var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages
2023-12-07 11:39:24.802923+0800 HelloWorld[668:221278] - /var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app
2023-12-07 11:39:24.802989+0800 HelloWorld[668:221278] Configure argc/argv...
2023-12-07 11:39:24.803048+0800 HelloWorld[668:221278] Initializing Python runtime...
2023-12-07 11:39:25.060379+0800 HelloWorld[668:221278] Installing Python NSLog handler...
2023-12-07 11:39:25.189759+0800 HelloWorld[668:221278] Running app module: helloworld
2023-12-07 11:39:25.617205+0800 HelloWorld[668:221278] ---------------------------------------------------------------------------
2023-12-07 11:39:31.728635+0800 HelloWorld[668:221278] App finished launching.

2023-12-07 11:39:31.821435+0800 HelloWorld[668:221278] Exception ignored on calling ctypes callback function: <rubicon.objc.api.objc_method object at 0x1043ebb50>

2023-12-07 11:39:31.822034+0800 HelloWorld[668:221278] Traceback (most recent call last):

2023-12-07 11:39:31.822428+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/rubicon/objc/api.py", line 335, in __call__

2023-12-07 11:39:31.823998+0800 HelloWorld[668:221278]     result = self.py_method(py_self, *args)

2023-12-07 11:39:31.824634+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/toga_iOS/app.py", line 37, in application_didFinishLaunchingWithOptions_

2023-12-07 11:39:31.825513+0800 HelloWorld[668:221278]     App.app.create()

2023-12-07 11:39:31.825855+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/toga_iOS/app.py", line 68, in create

2023-12-07 11:39:31.826888+0800 HelloWorld[668:221278]     self.interface._startup()

2023-12-07 11:39:31.827187+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/toga/app.py", line 624, in _startup

2023-12-07 11:39:31.828669+0800 HelloWorld[668:221278]     self.startup()

2023-12-07 11:39:31.829313+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app/HelloWorld/app.py", line 13, in startup

2023-12-07 11:39:31.831022+0800 HelloWorld[668:221278]     main_box = toga.Box(

2023-12-07 11:39:31.831437+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/toga/widgets/box.py", line 26, in __init__

2023-12-07 11:39:31.832466+0800 HelloWorld[668:221278]     self._impl = self.factory.Box(interface=self)

2023-12-07 11:39:31.832788+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/toga_iOS/widgets/base.py", line 17, in __init__

2023-12-07 11:39:31.833596+0800 HelloWorld[668:221278]     self.interface.style.reapply()

2023-12-07 11:39:31.833808+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/travertino/declaration.py", line 96, in reapply

2023-12-07 11:39:31.834402+0800 HelloWorld[668:221278]     self.apply(style, getattr(self, style))

2023-12-07 11:39:31.834758+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/toga/style/pack.py", line 117, in apply

2023-12-07 11:39:31.836005+0800 HelloWorld[668:221278]     Font(

2023-12-07 11:39:31.837288+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/toga/fonts.py", line 57, in __init__

2023-12-07 11:39:31.838477+0800 HelloWorld[668:221278]     self._impl = self.factory.Font(self)

2023-12-07 11:39:31.838893+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/toga_iOS/fonts.py", line 102, in __init__

2023-12-07 11:39:31.839598+0800 HelloWorld[668:221278]     font = UIFont.systemFontOfSize(size)

2023-12-07 11:39:31.839828+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/rubicon/objc/api.py", line 292, in __call__

2023-12-07 11:39:31.841772+0800 HelloWorld[668:221278]     return self.method(self.receiver, *args, **kwargs)

2023-12-07 11:39:31.842256+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/rubicon/objc/api.py", line 271, in __call__

2023-12-07 11:39:31.844633+0800 HelloWorld[668:221278]     return meth(receiver, *args)

2023-12-07 11:39:31.844980+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/rubicon/objc/api.py", line 213, in __call__

2023-12-07 11:39:31.845993+0800 HelloWorld[668:221278]     result = send_message(

2023-12-07 11:39:31.846344+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/rubicon/objc/runtime.py", line 844, in send_message

2023-12-07 11:39:31.848270+0800 HelloWorld[668:221278]     raise error

2023-12-07 11:39:31.848856+0800 HelloWorld[668:221278]   File "/var/containers/Bundle/Application/45919750-6E4D-4976-B82F-32715E67244C/HelloWorld.app/app_packages/rubicon/objc/runtime.py", line 837, in send_message

2023-12-07 11:39:31.850399+0800 HelloWorld[668:221278]     result = send(receiver, selector, *args, *varargs)

2023-12-07 11:39:31.851913+0800 HelloWorld[668:221278] ctypes.ArgumentError: systemFontOfSize: argument 3: <class 'TypeError'>: wrong type; argtypes: c_double

2023-12-07 11:39:32.431988+0800 HelloWorld[668:221278] App became active.

```

### Steps to reproduce

Shows a black screen when launch app on iPad Air(12.5.7). But, the iPhone(15.0+) is normal.

### Expected behavior

normal display

### Environment

- Operating System: macOS 14.1.2 (23B92)
- Python version:3.9.6
- Software versions:
  - Briefcase:0.3.16
  - Toga:0.4.0
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report. Unfortunately, I'm not able to reproduce this problem - your provided app runs fine for me on both the iPhone 15 Pro simulator and the iPad Air (5th gen) simulator.

The only part I *can't* reproduce is the old iOS version - Apple doesn't provide iOS 12 images easily available, and my personal iPads are all on iOS 17. It's possible there may have been a subtle API change, but it's difficult to confirm unless I can reproduce the problem.

The error that is being reported is saying that a value of type `c_double` was expected, but that isn't what has been provided. You might be able to get some more diagnosis detail by printing the value and type of `size` being passed in at line 102 of `app_packages/toga_iOS/fonts.py`, and working back from there to work out how that value was generated. You can use `briefcase open` to open the app in Xcode and make the debugging code change directly to the codebase.

**Comment by freakboy3742** [comment]
Ah - this is a problem we see from time to time.

The issue is that Objective C uses the same syntax for accessing a property, and invoking a method with no arguments. This means that they can transparently transform an argument-less method into a property without altering native Objective C usage; but Rubicon ObjC has an issue, because there's a difference in Python between `obj.attr` and `obj.attr()`.

Ordinarily, this would be caught when the iOS or macOS release that implements the change appears; existing usage will all be `UIFont.systemFontOfSize()`, and that stops working because it's no longer a method. However, in this case, we only added fonts recently, so the change in syntax wasn't ever observed in the "old" state.

The fix should be straightforward - if you modify `toga_iOS/libs/uikit.py`, looking for the UIFont declaration (around line 272):
```
UIFont = ObjCClass("UIFont")
```
and add an explicit declaration of the property:
```
UIFont = ObjCClass("UIFont")
UIFont.declare_class_property("systemFontOfSize")
```

that should resolve the issue.

If that works for you, let us know; wrapping that change up as a PR would be a great contribution!

**Comment by freakboy3742** [comment]
> Thanks. You are correct. And I commited pr, at #2265
> 
> But it should be `labelFontSize`

You're absolutely right. My apologies for the confusion, and thanks for the PR!
