### ISSUE TITLE
Error in handler: 'NoneType' object has no attribute 'name'  on Table on_select

### ISSUE THREAD

**Issue by Jigisuta** [beeware/toga#2551]
### Describe the bug

Below is the error I am getting:

`briefcase dev

[dataxtractor] Starting in dev mode...
===========================================================================
Test2
Error in handler: 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "C:\Users\nb\Documents\Zigisuta\DataExtractor\dataXtractor-venv\lib\site-packages\toga\handlers.py", line 80, in _handler
    result = handler(interface, *args, **kwargs)
  File "C:\Users\nb\Documents\Zigisuta\DataExtractor\dataxtractor\src\dataxtractor\app.py", line 23, in clicked
    print(table.selection.name  )
AttributeError: 'NoneType' object has no attribute 'name'
Test3
Error in handler: 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "C:\Users\nb\Documents\Zigisuta\DataExtractor\dataXtractor-venv\lib\site-packages\toga\handlers.py", line 80, in _handler
    result = handler(interface, *args, **kwargs)
  File "C:\Users\nb\Documents\Zigisuta\DataExtractor\dataxtractor\src\dataxtractor\app.py", line 23, in clicked
    print(table.selection.name  )
AttributeError: 'NoneType' object has no attribute 'name'
TestUser`

### Steps to reproduce

```
def editOracleConAction(widget):
  popup = toga.Window(title="Editor")
  def clicked(table):
      print(table.selection.name  )
  
  tbl_data=list((('Test2','hostnameTest'),('Test3','hostname@Test'),('TestUser','test@hostname')))
  connectionTable = toga.Table(id="connTableId",multiple_select=False, headings=['Name', 'Conn Details'],style=Pack(flex=1, width=200), data=tbl_data, on_select=clicked)
```
        

### Expected behavior

Test2
Test3
TestUser

### Environment

- Operating System: Windows 10
- Python version: 3.10.2
- Software versions:
  - Briefcase: 0.3.0
  - Toga: 0.4.2
  - ...

### Logs

```

```

**Comment by rmartin16** [comment]
Reproduced on `main` on Windows...but not with GTK. Looks like the handler is being executed twice.

**Comment by freakboy3742** [comment]
This is at least partially an error of usage - a selection value of `None` is valid.

This specific manifestation of the *might* be considered a bug; my guess is that there are 2 events - one indicating a loss of selection (to nothing), and one indicating the new selection. I agree it would be nice for a direct change from selecting from one row to another didn't generate 2 events, but it's also not *strictly* wrong, and any selection management code should handle the `None` case.

**Comment by Jigisuta** [comment]
@freakboy3742.. Thank you for your response. 

Is there any workaround to avoid the error? 
The error is not affecting the code, but my log window is full of this error, and the size of the log file is getting bigger.

**Comment by reefwing** [comment]
Can't you just check if the selection is `None` before you try to use it? For example:

```
def editOracleConAction(widget):
    popup = toga.Window(title="Editor")

    def clicked(table):
        # Check if there is a selected row
        if table.selection:
            # Assuming the first column is 'Name'
            print(table.selection[0])
        else:
            print("No row selected")

    tbl_data = [('Test2', 'hostnameTest'), ('Test3', 'hostname@Test'), ('TestUser', 'test@hostname')]
    connectionTable = toga.Table(
        id="connTableId",
        multiple_select=False,
        headings=['Name', 'Conn Details'],
        style=Pack(flex=1, width=200),
        data=tbl_data,
        on_select=clicked
    )

    popup.content = connectionTable
    popup.show()
```

**Comment by Jigisuta** [comment]
@reefwing Yes, I also thought of that, I will try to implement it today. 

Thanks for the help
