### ISSUE TITLE
Intermittent "MapView web canvas didn't initialize" error in Windows CI

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#2632]
This isn't happening as often as the intermittent macOS failures (#2512 and #2631), but I've seen it at least 4 times over the last month. Here are the two most recent ones:

* https://github.com/beeware/toga/actions/runs/9412582279/job/25927877053
* https://github.com/beeware/toga/actions/runs/9161980104/job/25188282375

```
=================================== ERRORS ====================================
___________________ ERROR at setup of test_flex_widget_size ___________________
Traceback (most recent call last):
  File "D:\a\toga\toga\testbed\build\testbed\windows\app\src\app_packages\pytest_asyncio\plugin.py", line 299, in _asyncgen_fixture_wrapper
    result = event_loop.run_until_complete(setup())
  File "D:\a\toga\toga\testbed\build\testbed\windows\app\src\app\tests\conftest.py", line 96, in run_until_complete
    return asyncio.run_coroutine_threadsafe(coro, self.loop).result()
  File "concurrent\futures\_base.py", line 458, in result
  File "concurrent\futures\_base.py", line 403, in __get_result
  File "D:\a\toga\toga\testbed\build\testbed\windows\app\src\app_packages\pytest_asyncio\plugin.py", line 281, in setup
    res = await gen_obj.__anext__()
  File "D:\a\toga\toga\testbed\build\testbed\windows\app\src\app\tests\widgets\test_mapview.py", line 53, in widget
    raise RuntimeError("MapView web canvas didn't initialize")
RuntimeError: MapView web canvas didn't initialize
=========================== short test summary info ===========================
ERROR tests/widgets/test_mapview.py::test_flex_widget_size - RuntimeError: MapView web canvas didn't initialize
======= 417 passed, 45 skipped, 4 xfailed, 1 error in 218.74s (0:03:38) =======
```

**Comment by freakboy3742** [comment]
I've seen this one too; however, my read is that this might be outside our control. We get a bunch of failures that amount to "Github's CI machine falls off the network" - failures contacting the Ubuntu package server etc. It's disturbing how often this happens, but I'm not sure there's much we can do about it when it does, other than perhaps increasing retries and timeouts.

**Comment by mhsmith** [comment]
I used to have similar problems in the Chaquopy CI, and I found some discussion which led me to [this action](https://github.com/smorimoto/tune-github-hosted-runner-network) which I now run at the [start of every job](https://github.com/chaquo/chaquopy/blob/c556bb2817f55c30ad9b3402295f2623aca461bd/.github/workflows/ci.yml#L19). Since then, the problems have completely disappeared.

**Comment by freakboy3742** [comment]
Interesting... can't hurt to try adding that one in, I guess...

**Comment by mhsmith** [comment]
Still happening, unfortunately: https://github.com/beeware/toga/actions/runs/9589159070/job/26442549519

**Comment by freakboy3742** [comment]
A very closely related problem happens even more intermittently on GTK (see [this comment](https://github.com/beeware/toga/pull/2812#issuecomment-2327259847)).

**Comment by freakboy3742** [comment]
I don't think we've seen this for a while; closing.
