### ISSUE TITLE
Tutorial 4 crash Windows

### ISSUE THREAD

**Issue by ibigpapa** [beeware/toga#498]
## Expected Behavior

expect tutorial 4 to load

## Current Behavior

tutorial4 crashes before loading
Unhandled Exception: Python.Runtime.PythonException: AttributeError : module 'toga_winforms.factory' has no attribute 'Canvas'
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

## Steps to reproduce

1. launch tutorial 4

## Your Environment

* Python Version (list the specific version number) 3.6.5

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [x ] Windows - version: win10 1607
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [x ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Asyncio support now exists for Windows.
