### ISSUE TITLE
Progressbar crash on start

### ISSUE THREAD

**Issue by ibigpapa** [beeware/toga#504]
## Expected Behavior

Progress bar to load

## Current Behavior

```
python -m progressbar
Unhandled Exception: Python.Runtime.PythonException: TypeError : 'NoneType' value cannot be converted to System.Int32
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
## Steps to reproduce

1. launch progressbar

## Your Environment

* Python Version (list the specific version number) 3.6.5

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [ * ] Windows - version: Win10 1607
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ * ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by saroad2** [comment]
Had the same error when tried to run the "progressbar" example on windows. Had the following error:

```
Traceback (most recent call last):
  File "c:\users\saroa\repositories\toga\src\winforms\toga_winforms\app.py", line 143, in run_app
    self.create()
  File "c:\users\saroa\repositories\toga\src\winforms\toga_winforms\app.py", line 65, in create
    self.interface.startup()
  File "C:\Users\saroa\repositories\toga\examples\progressbar\progressbar\app.py", line 16, in startup
    self.progress_runner = toga.ProgressBar(max=None)
  File "c:\users\saroa\repositories\toga\src\core\toga\widgets\progressbar.py", line 34, in __init__
    self.max = max
  File "c:\users\saroa\repositories\toga\src\core\toga\widgets\progressbar.py", line 113, in max
    self._impl.set_max(value)
  File "c:\users\saroa\repositories\toga\src\winforms\toga_winforms\widgets\progressbar.py", line 27, in set_max
    self.native.Maximum = value
TypeError: 'NoneType' value cannot be converted to System.Int32
```

What should be the right behavior when "max" is set to None?
Maybe I could implement it.

**Comment by freakboy3742** [comment]
macOS handles the "max=None" case as "this is a progress bar of indeterminate length", and displays a "throbbing bar".
