### ISSUE TITLE
ModuleNotFoundError: No module named 'toga.django'

### ISSUE THREAD

**Issue by sanjaykhanssk** [beeware/toga#576]
ModuleNotFoundError: No module named 'toga.django'
 * Starting Django server on localhost:8042
 * Opening browser...
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'toga.django'

**Comment by danyeaw** [comment]
@sanjaykhanssk Thanks for the issue report. Unfortunately the current development version needs a lot of work on the Django backend. Which version of Toga do you have installed?

**Comment by freakboy3742** [comment]
Closing on the basis that there isn't anything especially actionable here.
