### ISSUE TITLE
returned non-zero exit status 1

### ISSUE THREAD

**Issue by StjepanVinski** [beeware/toga#593]
I created an initial HelloWorld App. Now I'm trying to create an Windows app with a command "python setup.py windows" and i get the following error:

running windows
 * Writing application template...
Template Python-Windows-template succesfully updated.
Project template: C:\Users\stjepanv/.cookiecutters/Python-Windows-template
 * Determining best support package...
 * Installing support package...
Support package: https://www.python.org/ftp/python/3.5.4/python-3.5.4-embed-win32.zip
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    'toga-django==0.3.0.dev9',
  File "c:\users\stjepanv\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "c:\users\stjepanv\appdata\local\programs\python\python35-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\users\stjepanv\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "c:\users\stjepanv\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\users\stjepanv\appdata\local\programs\python\python35-32\lib\site-packages\briefcase\app.py", line 477, in run
    self.install_platform_requirements()
  File "c:\users\stjepanv\appdata\local\programs\python\python35-32\lib\site-packages\briefcase\app.py", line 298, in install_platform_requirements
    stderr=subprocess.STDOUT,
  File "c:\users\stjepanv\appdata\local\programs\python\python35-32\lib\subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "c:\users\stjepanv\appdata\local\programs\python\python35-32\lib\subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pip', 'install', '--upgrade', '--force-reinstall', '--target=C:\\Users\\stjepanv\\AppData\\Local\\Programs\\Python\\Python35-32\\appname\\windows\\content\\app_packages', 'toga-winforms==0.3.0.dev9']' returned non-zero exit status 1

**Comment by MisterY** [comment]
If I may suggest:

- which version of pythonnet do you have installed?
- could you try upgrading toga libraries to dev11 and then run the same command?

I'm on Python 3.7, Toga 0.3.0-dev11, pythonnet 2.4.0dev0 (for 3.7 support), and I'm getting different issues trying to package the windows application. I think the issue is with pythonnet, though. At least in my case.

**Comment by freakboy3742** [comment]
Closing due to inactivity, combined with a singificant change in the tooling around winforms packaging.
