### ISSUE TITLE
Exceptions in Tutorial 0 after clean install

### ISSUE THREAD

**Issue by Aareon** [beeware/toga#598]
## Your Environment
* Python Version: 3.6.6 (clean virtual environment)
* OS and Version: Windows 10 Pro Version 10.0.17134 Build 17134
* Toga Target: win32

## Other Information
* `pip 10.0.1 from e:\users\aareon\project\venv\lib\site-packages\pip (python 3.6)`
* No other installed packages: `pip freeze` returns nothing before installing `toga`
* Installed `toga` with
```ps
.\venv\Scripts\activate
pip install --pre toga
```
* Installing `toga` with `pip install toga` works "fine", except some relatively weird behaviors (as to be expected, such as the button fills the whole window, no window icon, etc.)

## Test Code (same as found on https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html)
```py
import toga


def button_handler(widget):
    print('hello')


def build(app):
    box = toga.Box()

    button = toga.Button('Hello, World!', on_press=button_handler)
    button.style.padding = 50
    button.style.flex = 1
    box.add(button)

    return box


def main():
    return toga.App('First App', 'org.pybee.helloworld', startup=build)


if __name__ == '__main__':
    main().main_loop()
```

### toga.button
```py
Traceback (most recent call last):
  File ".\helloworld.py", line 77, in <module>    main().main_loop()  File ".\helloworld.py", line 73, in main
    return toga.App('First App', 'org.pybee.helloworld', startup=build)  File "E:\Users\Aareon\Documents\Programming\Python\IDE\venv\lib\site-packages\toga\app.py", line 53, in __init__    self.factory = get_platform_factory(factory)
  File "E:\Users\Aareon\Documents\Programming\Python\IDE\venv\lib\site-packages\toga\platform.py", line 42, in get_platform_factory    from toga_winforms import factory
  File "E:\Users\Aareon\Documents\Programming\Python\IDE\venv\lib\site-packages\toga_winforms\factory.py", line 9, in <module>
    from .widgets.button import Button
  File "E:\Users\Aareon\Documents\Programming\Python\IDE\venv\lib\site-packages\toga_winforms\widgets\button.py", line 3, in <module>
    from toga_winforms.resources.colors import native_color
ModuleNotFoundError: No module named 'toga_winforms.resources'
```
> Fixed by changing [toga_winforms.button line 3](https://github.com/pybee/toga/blob/master/src/winforms/toga_winforms/widgets/button.py#L3) to `from toga_winforms.colors import native_color`

### toga_winforms.colors
```py
Traceback (most recent call last):
  File ".\helloworld.py", line 88, in <module>
    main().main_loop()
  File ".\helloworld.py", line 84, in main
    return toga.App('First App', 'org.pybee.helloworld', startup=build)
  File "E:\Users\Aareon\Documents\Programming\Python\IDE\venv\lib\site-packages\toga\app.py", line 53, in __init__
    self.factory = get_platform_factory(factory)
  File "E:\Users\Aareon\Documents\Programming\Python\IDE\venv\lib\site-packages\toga\platform.py", line 42, in get_platform_factory
    from toga_winforms import factory
  File "E:\Users\Aareon\Documents\Programming\Python\IDE\venv\lib\site-packages\toga_winforms\factory.py", line 9, in <module>
    from .widgets.button import Button
  File "E:\Users\Aareon\Documents\Programming\Python\IDE\venv\lib\site-packages\toga_winforms\widgets\button.py", line 3, in <module>
    from toga_winforms.colors import native_color
  File "E:\Users\Aareon\Documents\Programming\Python\IDE\venv\lib\site-packages\toga_winforms\colors.py", line 1, in <module>
    from ..libs import Color
ValueError: attempted relative import beyond top-level package
```
> Fixed by changing [toga_winforms.colors line 1](https://github.com/pybee/toga/blob/master/src/winforms/toga_winforms/colors.py#L1) to `from toga_winforms.libs import Color`
>> Note: `from .libs import Color` is also an acceptable fix, but be mindful that some linters don't like relative imports, so a `#NOQA` shebang after these imports will be necessary for accurate linting.

### toga.icons
```py
[Winforms] No valid icon format available for E:\Users\Aareon\Documents\Programming\Python\IDE\venv\lib\site-packages\resources\tiberius; fall back on Tiberius instead
Unhandled Exception: Python.Runtime.PythonException: DirectoryNotFoundException : Could not find a part of the path 'E:\Users\Aareon\Documents\Programming\Python\IDE\venv\lib\site-packages\resources\tiberius.ico'.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
> Fixed by changing [toga.icons line 38](https://github.com/pybee/toga/blob/master/src/core/toga/icons.py#L38) to `toga_dir = os.path.dirname(__file__)`

**Comment by freakboy3742** [comment]
Thanks for the report - looks like you've found a problem with a recent code refactor that slipped past our testing. It looks like you've identified the key problems, and might even be working on a pull request - is that correct?

**Comment by Aareon** [comment]
That would be correct. I just wanted to make sure I had all of my ducks in a row before I pushed anything.

I looked a little bit, but anything I need to know about PR guidelines here? It seems these change per repo. Just want to make sure I get it right the first time.

**Comment by freakboy3742** [comment]
There aren't any specific PR guidelines - any PR that is a net improvement to the codebase and passes CI will be probably be accepted. 

If you're able to add tests that would prevent the bug from re-appearing, that would be amazing. However, testing GUI code can be difficult, so if you can't work out an obvious test, it's fine to skip that step.

**Comment by Aareon** [comment]
Well, I might be able to work something out. Testing path handling seems a little awkward. I’m not terribly familiar with TDD.

To be honest with you, I’m not sure how it’s passing tests right now. You would think these types of errors would be caught right away :\

**Comment by freakboy3742** [comment]
The problems reported by this ticket have since been resolved.
