### ISSUE TITLE
what's this mean?what should I do?

### ISSUE THREAD

**Issue by wangyang2010344** [beeware/toga#627]

**Comment by wangyang2010344** [comment]
% python3 f.py                                                          !8418
Traceback (most recent call last):
  File "f.py", line 24, in <module>
    main().main_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/toga_cocoa/app.py", line 167, in main_loop
    self._startup()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/toga_cocoa/app.py", line 100, in _startup
    self.resource_path = os.path.dirname(os.path.dirname(NSBundle.mainBundle.bundlePath))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not ObjCBoundMethod

**Comment by wangyang2010344** [comment]
% toga-demo                                                             !8419
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/toga-demo", line 11, in <module>
    sys.exit(run())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/toga_demo/__main__.py", line 5, in run
    main().main_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/toga_cocoa/app.py", line 167, in main_loop
    self._startup()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/toga_cocoa/app.py", line 100, in _startup
    self.resource_path = os.path.dirname(os.path.dirname(NSBundle.mainBundle.bundlePath))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not ObjCBoundMethod

**Comment by wangyang2010344** [comment]
I am in OS X 10.8 and xcode 4.6

**Comment by freakboy3742** [comment]
Ah - that will be the source of the problem then. I'm *definitely* not testing on old versions of macOS - and 10.8 is quite old at this point.

If you want to try fixing this bug, the solution will look something like this: 

https://github.com/pybee/toga/commit/058dcca532676c24ecb2e2425057e50685ce88cd

but affecting the "bundlePath" attribute of NSBundle. From the look of it, the issue may just be the missing brackets on the call to bundlePath - you can see if fixing that addresses your problem.

**Comment by Aareon** [comment]
Seeing as this issue is quite stale and no one has stepped up to fix it, should this issue be closed?

**Comment by freakboy3742** [comment]
If someone wants to submit a PR maintaining support for Mountain Lion (or any other historical release), I'll gladly merge it; otherwise, I'm going to close this ticket.
