### ISSUE TITLE
toga.Window().show() not working in macOS

### ISSUE THREAD

**Issue by yingw787** [beeware/toga#668]
## Expected Behavior

I was trying to debug issue #646 by first reproducing and found that the macOS Window() was broken of HEAD of mainline.

The file I was trying to run was:

```python
import toga

window = toga.Window('my window', title='This is a window')

window.show()
```

This is from the reference in the [BeeWare tutorial](https://toga.readthedocs.io/en/latest/reference/api/window.html):

The test coverage seems to be low for toga-cocoa.

## Current Behavior

Right now, when I run the file with `python -m toga_file_dialog`, I get back the stack trace:

```python
Traceback (most recent call last):
  File "/Users/yingwang/anaconda3/envs/toga/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/yingwang/anaconda3/envs/toga/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/yingwang/python_projects/my_pycon_sprint_forks/toga-tutorial/toga_file_dialog.py", line 5, in <module>
    window.show()
  File "/Users/yingwang/python_projects/my_pycon_sprint_forks/toga/src/core/toga/window.py", line 166, in show
    self._impl.show()
  File "/Users/yingwang/python_projects/my_pycon_sprint_forks/toga/src/cocoa/toga_cocoa/window.py", line 210, in show
    self.native.makeKeyAndOrderFront(None)
AttributeError: 'NoneType' object has no attribute 'style'
```

## Steps to reproduce
1. Create file `toga_file_dialog.py`

2. Add in code snippet

3. Run with steps listed in bug trace:

## Your Environment

* Python Version (list the specific version number):

```bash
(toga) Yings-Macbook-Pro:toga-tutorial yingwang$ python --version
Python 3.7.3
```

Using a `conda` environment generated by command: `conda create -n toga python=3.7`, with pip install steps from beeware tutorial.

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [X] macOS - version:

```bash
(toga) Yings-Macbook-Pro:toga-tutorial yingwang$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1815
```

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [X] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

Will see whether I can contribute a fix and test coverage for test_window.py in toga-cocoa.

**Comment by yingw787** [comment]
`toga.window.Window` must be wrapped in `toga.app.App`. I updated the documentation so as to provide a standalone code snippet.

If you close the window and reopen it by clicking on the app icon in the menu bar, there is an issue with reopening due to an issue with `self.impl.select_file()`:

```python
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/Users/yingwang/anaconda3/envs/toga/lib/python3.7/site-packages/rubicon/objc/api.py", line 232, in __call__
    result = self.py_method(py_self, *args)
  File "/Users/yingwang/python_projects/my_pycon_sprint_forks/toga/src/cocoa/toga_cocoa/app.py", line 35, in applicationOpenUntitledFile_
    self.impl.select_file()
AttributeError: 'App' object has no attribute 'select_file'
```

After some further manual testing, I don't think this is related to `toga.window.Window` not opening.

**Comment by freakboy3742** [comment]
It looks to me that this a function of trying to open a Window without an application.
