### ISSUE TITLE
Third code example from tutorial will not run

### ISSUE THREAD

**Issue by pythoniac** [beeware/toga#71]
I am on Ubuntu Linux and get the following errors:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/toga_gtk/widgets/icon.py", line 27, in __impl
    return self._impl_cache[size]
KeyError: 32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/toga_gtk/app.py", line 139, in _startup
    self.startup()
  File "/usr/local/lib/python3.5/dist-packages/toga/interface/app.py", line 59, in startup
    self.main_window.content = self._startup_method(self)
  File "third_example.py", line 88, in build
    cmd4
  File "/usr/local/lib/python3.5/dist-packages/toga/interface/window.py", line 76, in toolbar
    self._set_toolbar(items)
  File "/usr/local/lib/python3.5/dist-packages/toga_gtk/window.py", line 42, in _set_toolbar
    item_impl.set_icon_widget(toolbar_item.icon._impl_32)
  File "/usr/local/lib/python3.5/dist-packages/toga_gtk/widgets/icon.py", line 35, in <lambda>
    _impl_32 = property(lambda self: self.__impl(32))
  File "/usr/local/lib/python3.5/dist-packages/toga_gtk/widgets/icon.py", line 30, in __impl
    GdkPixbuf.Pixbuf.new_from_file(self._filename).scale_simple(size, size, GdkPixbuf.InterpType.BILINEAR)
GLib.Error: g-file-error-quark: Failed to open file 'icons/brutus.icns': No such file or directory (4)

**Comment by albe-rosado** [comment]
looks like in the __init__ method in icon.py, the path where brutus.ics is, wasn't included.

**Comment by freakboy3742** [comment]
This appears to have been resolved.
