### ISSUE TITLE
Can I run main_loop in separate process/thread [Windows]?

### ISSUE THREAD

**Issue by UncleGoogle** [beeware/toga#734]
## Question
I would like to run my app in separate thread or process (as a workaround for yet not available asyncio compatibility #68 ).

Does it possible without spawning external process by `subprocess`? I don't know where is is the user python installed.

## Problem with threading
```python
import toga
import threading
app = toga.App('Name', 'org.app.id', startup=lambda _: None)
gui = threading.Thread(target=app.main_loop)
gui.start()
```
I got:
```
$ python -m src.keysgui
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\users\mesco\appdata\local\programs\python\python37-32\Lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\mesco\appdata\local\programs\python\python37-32\Lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mesco\Workspace\galaxy-integration-humblebundle\.venv\lib\site-packages\toga\app.py", line 186, in main_loop
    signal.signal(signal.SIGINT, signal.SIG_DFL)
  File "c:\users\mesco\appdata\local\programs\python\python37-32\Lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

## Problem with multiprocessing
```python
import toga
import multiprocessing
app = toga.App('Name', 'org.app.id', startup=lambda _: None)
gui = multiprocessing.Process(target=app.main_loop)
gui.start()
```
This results in error:
```
python -m src.keysgui
Traceback (most recent call last):
  File "c:\users\mesco\appdata\local\programs\python\python37-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mesco\appdata\local\programs\python\python37-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\mesco\Workspace\galaxy-integration-humblebundle\src\keysgui.py", line 76, in <module>
    gui.start()
  File "c:\users\mesco\appdata\local\programs\python\python37-32\Lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "c:\users\mesco\appdata\local\programs\python\python37-32\Lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\users\mesco\appdata\local\programs\python\python37-32\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\users\mesco\appdata\local\programs\python\python37-32\Lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\users\mesco\appdata\local\programs\python\python37-32\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle module objects
(.venv) mesco@DESKTOP-023dfJDD MINGW64 ~/***/*** 
$ Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\mesco\appdata\local\programs\python\python37-32\Lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\users\mesco\appdata\local\programs\python\python37-32\Lib\multiprocessing\reduction.py", line 82, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] The parameter is incorrect
```

Can you help me to find the solution?

## Environment

* Python Version (list the specific version number)
3.7.2

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version:
  - [ ] Linux - distro:   - version:
  - [x] Windows - version: Windows 10
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
0.3.dev14

**Comment by freakboy3742** [comment]
GUI programs are, by their nature, a bit greedy - they expect to be "in control", because they're interacting with the operating system at a fairly close level. Although the error you're currently seeing ("signal only works in main thread") is a direct invocation by Toga, I strongly suspect that even if we removed that call, you'd see similar errors from trying to start the GUI main loop in the non-main thread.

My suggestion would be to spin this around; rather than trying to run the *app* in a separate thread, run your "other" code in a separate thread, spawned as part of the startup process. There will be some limits to what is possible here; you won't be able to invoke any GUI operations from the second thread. Winforms expects all GUI operations to occur on the main thread; so you'll need to find a way to inject those requests into the main GUI thread (I'm not a winforms expert, but I think the Invoke() method is the native mechanism here).

Multiprocessing is likely to have problems either way in this case; multiprocessing depends on being able to pickle the entire state of a process and reconstitute it, and the GUI libraries that we're using don't survive that pickling. You might have more luck using raw fork/spawn/exec calls - but you'll also need to do your own cross-process communication handling with pipe etc.

**Comment by UncleGoogle** [comment]
Thanks for explanation. I saw similar problems with other gui systems on the stackoverflow.

In my case it is impossible to run gui first, because of nature of my code is standardized plugin (https://github.com/gogcom/galaxy-integrations-python-api) running by other app, and should be non-blocking.

Currently I've workaround this problem as you said; no need communication with the process yet. Code for others:
```python
async def install_game(self, game_id):
    # (...)
    process = await asyncio.create_subprocess_exec(sys.executable, *args, stderr=asyncio.subprocess.PIPE)
    stdout_data, stderr_data = await process.communicate()
    if stderr_data:
        logging.debug(stderr_data)
```

**Comment by freakboy3742** [comment]
Ah - that's an interesting use case - you've got *yet another* event loop involved (the GOG event loop). I'd be interested in hearing how other windowing systems work around the main thread limitations.
