### ISSUE TITLE
Can't run toga demo with latest toga sources [7da768ea]

### ISSUE THREAD

**Issue by BrendanSimon** [beeware/toga#806]
## Expected Behavior

Run toga demo (`python -m toga_demo`) with toga installed from sources, and see the demo window appear.

## Current Behavior

No demo window appears and an exception backtrace is output to console.

```
(venv3.7) $ python -m toga_demo
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/brendan/Sandbox/beeware/toga/demo/toga_demo/__main__.py", line 8, in <module>
    run()
  File "/Users/brendan/Sandbox/beeware/toga/demo/toga_demo/__main__.py", line 5, in run
    main().main_loop()
  File "/Users/brendan/Sandbox/beeware/toga/src/core/toga/app.py", line 406, in main_loop
    self._impl.main_loop()
  File "/Users/brendan/Sandbox/beeware/toga/src/cocoa/toga_cocoa/app.py", line 185, in main_loop
    self.create()
  File "/Users/brendan/Sandbox/beeware/toga/src/cocoa/toga_cocoa/app.py", line 125, in create
    self.interface.startup()
  File "/Users/brendan/Sandbox/beeware/toga/demo/toga_demo/app.py", line 59, in startup
    split.content = [left_container, right_container]
  File "/Users/brendan/Sandbox/beeware/toga/src/core/toga/widgets/splitcontainer.py", line 67, in content
    widget.window = self.window
  File "/Users/brendan/Sandbox/beeware/toga/src/core/toga/widgets/base.py", line 121, in window
    content.window = window
AttributeError: 'list' object has no attribute 'window'
(venv3.7) $ 
```

**NOTE: the same demo sources run ok using toga from PyPi.**

## Steps to reproduce

1. Uninstall any toga modules.

2. Install toga modules from sources
    - `pip install -e src/core`
    - `pip install -e src/dummy`
    - `pip install -e src/cocoa`

3. Run demo: `python -m toga_demo`

## Environment

* Python Version 3.7.6 (os x)

* OS X Catalina (10.15.3)

**Comment by freakboy3742** [comment]
Thanks for the report - looks like a bug introduced by the fix for #795 that landed yesterday. 

We really need a unit test framework for GUI stuff...

**Comment by BrendanSimon** [comment]
A long time ago i came across these suite of tools and always thought they sounded quite interesting (but never used them).

- StoryText ( http://texttest.sourceforge.net/index.php?page=ui_testing )
- TextTest ( http://texttest.sourceforge.net )
- CaptureMock ( http://texttest.sourceforge.net/index.php?page=capturemock )

They are both available on PyPi - but they seem to dormant since 2015.

**Comment by BrendanSimon** [comment]
Yep.  Working again.  Thanks.

**Comment by BrendanSimon** [comment]
Could this problem have been caught if the testing mocked the low level native APIs (i.e. 3rd party APIs) instead of mocking the high level Toga API?

Could toga dummy have dummy implementations for each target API?  That would at least test all the code logic above the 3rd party APIs.

**Comment by freakboy3742** [comment]
In this case, yes. The issue was in the interface layer, and some assumptions it made about content handling in containers; so even a test of "start the app with the dummy backend" would have caught the problem. 

We're missing a little bit of infrastructure that would allow us to *write* such a test... but not *that* much.
