### ISSUE TITLE
NSAlert when trying to run a deployed app

### ISSUE THREAD

**Issue by robinsiebler** [beeware/toga#952]
I build a very simple app. I packaged it into a .dmg file, put that on another Mac, "installed" in and tried to run it. No bueno! When I ran it from the console, I get this error:

```
local@locals-MacBook-Pro Downloads % /Applications/Plex\ Library\ Viewer.app/Contents/MacOS/Plex\ Library\ Viewer 
Traceback (most recent call last):
  File "/Applications/Plex Library Viewer.app/Contents/Resources/Support/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Applications/Plex Library Viewer.app/Contents/Resources/Support/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Applications/Plex Library Viewer.app/Contents/Resources/app/plexlibraryviewer/__main__.py", line 4, in <module>
    main().main_loop()
  File "/Applications/Plex Library Viewer.app/Contents/Resources/app/plexlibraryviewer/app.py", line 63, in main
    return MainWindow()
  File "/Applications/Plex Library Viewer.app/Contents/Resources/app_packages/toga/app.py", line 208, in __init__
    self.factory = get_platform_factory(factory)
  File "/Applications/Plex Library Viewer.app/Contents/Resources/app_packages/toga/platform.py", line 31, in get_platform_factory
    from toga_cocoa import factory
  File "/Applications/Plex Library Viewer.app/Contents/Resources/app_packages/toga_cocoa/factory.py", line 1, in <module>
    from .app import App, DocumentApp, MainWindow
  File "/Applications/Plex Library Viewer.app/Contents/Resources/app_packages/toga_cocoa/app.py", line 13, in <module>
    from .keys import cocoa_key
  File "/Applications/Plex Library Viewer.app/Contents/Resources/app_packages/toga_cocoa/keys.py", line 3, in <module>
    from toga_cocoa.libs import (
  File "/Applications/Plex Library Viewer.app/Contents/Resources/app_packages/toga_cocoa/libs/__init__.py", line 1, in <module>
    from .appkit import *  # noqa: F401, F403
  File "/Applications/Plex Library Viewer.app/Contents/Resources/app_packages/toga_cocoa/libs/appkit.py", line 24, in <module>
    NSAlert = ObjCClass('NSAlert')
  File "/Applications/Plex Library Viewer.app/Contents/Resources/app_packages/rubicon/objc/api.py", line 734, in __new__
    ptr, name = cls._new_from_name(name_or_ptr)
  File "/Applications/Plex Library Viewer.app/Contents/Resources/app_packages/rubicon/objc/api.py", line 642, in _new_from_name
    raise NameError("ObjC Class '%s' couldn't be found." % name)
NameError: ObjC Class 'b'NSAlert'' couldn't be found.
```
Attached you will find my project.
[bug.zip](https://github.com/beeware/beeware/files/4834215/bug.zip)

**Comment by freakboy3742** [comment]
Transferred from beeware/beeware on the basis that it's not a problem with the tutorial, and likely a Toga problem.

@robinsiebler How do you reproduce this bug? Your sample project is working fine for me, under `briefcase dev`, `briefcase run`, and starting from the icon. I'm using macOS Mojave, Python 3.8.

The failure you're reporting is effectively Rubicon reporting that it can't find the NSAlert class in the Objective C runtime... which shouldn't be happening on *any* Mac running anything after macOS 10.3. The only way I can think that this would be occurring is if you're doing something fundamentally odd with your macOS runtime libraries, but I have no idea what that would be.

**Comment by robinsiebler** [comment]
I guess something must be weird with that partition, because I got my app to run on another partition.

**Comment by freakboy3742** [comment]
Closing as the original reporter has evidently resolved the problem.
