### ISSUE TITLE
Icons for tutorial 2 not being picked up

### ISSUE THREAD

**Issue by brettcannon** [beeware/toga#990]
**Describe the bug**
Unzipping the icons file as pointed to by https://toga.readthedocs.io/en/latest/tutorial/tutorial-2.html does not lead to the icons being picked up:
```
WARNING: Can't find icon icons/brutus; falling back to default icon
WARNING: Can't find icon icons/cricket-72.png; falling back to default icon
WARNING: Can't find icon icons/brutus; falling back to default icon        
WARNING: Can't find icon icons/brutus; falling back to default icon        
```

**To Reproduce**
1. Go to https://toga.readthedocs.io/en/latest/tutorial/tutorial-2.html
2. Copy over the code from the tutorial
3. Unzip https://toga.readthedocs.io/en/latest/_downloads/d3cc510fb784d45459de5a897e8b91b2/icons.zip
4. Move the `icons` directory to where your code is kept

**Expected behavior**
The new icons to be picked up.

**Environment:**
 - Operating System: Windows 10
 - Python version: Python 3.8.3
 - Software versions:
   - Briefcase:
   - Toga: 0.3.0.dev22
   - ...

**Additional context**
Poking around with the code suggests that there's potentially two problems. One is the `brutus` icon is named `brutus.icns` and not `brutus.ico`. The second issue is that `factory.paths.app` in `taga.icons.Icon.bind()` is pointing at not where the app code is but `site-packages/toga`.

**Comment by freakboy3742** [comment]
The `brutus.ico` looks like it's a missing resource - we haven't added an icon in Windows format to the resource set in the demo.

The path problem probably stems from something in the core of the app failing to identify its execution module. Out of interest - how were you starting the demo app? (i.e., `briefcase dev`, `python -m tutorial`, `python tutorial/app.py`...)

**Comment by brettcannon** [comment]
With `-m`.

**Comment by freakboy3742** [comment]
Turns out the path issue was a red herring; what you were seeing is the fallback location. Since the requested icon didn't exist, Toga was falling back to a "known good" location.

**Comment by bsanderson1981** [comment]
What is the known good location [default] location toga is looking for icons?   since I am having same issue with tutorial 3  boxes.  tried full path to ic

WARNING: Can't find icon /beeware-tutorial/toga/cricket-72.png; falling back to default icon
WARNING: Can't find icon icons/cricket-72.png; falling back to default icon
WARNING: Can't find icon icons/brutus; falling back to default icon
WARNING: Can't find icon cricket-72.png; falling back to default icon

**Comment by freakboy3742** [comment]
@bsanderson1981 It depends which icon you're loading, and the platform you're on. It looks like you're on Linux (which uses png format by default for icons); on Linux, Toga will look for the *app* icon as `resources/{app_name}-72.png` - so, in the case of tutorial 3, it will look for `resources/tutorial-72.png`. It will look for the folder relative to the folder where the app itself is defined.

The boxes tutorial (which is Tutorial 2 - I presume that was a typo) also loads some additional icons (the brutus and cricket references). I haven't run tutorial 2 on Linux for a while, so it's possible something has gotten out of alignment.

**Comment by bsanderson1981** [comment]
yes on Ubuntu 20.04.1 LTS  will retest tutorial 3  and let you now if tutorial 2 is out or working on....  thanks,.

**Comment by bsanderson1981** [comment]
I have not been able to get the default  icons from tutorial [You put the box inside another box]…to show up.  Even putting them in same directory as default toga.ico.    
cricket72-png 

I was looking at icon.py  see if I can debug it for my setup.   
sorry not more helpful but 3 month into python myself..   

I did find that if you rename toga.ico  to anything else.  tutorial will not run...   lots of run errors in terminal...  

terminal errors when you rename resource/toga.ico:::::

  raise FileNotFoundError(
FileNotFoundError: Can't find icon resources/toga

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/pathlib.py", line 713, in __str__
    return self._str
AttributeError: _str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bsanderson11/Documents/DevHub/code/toga/venv/lib/python3.8/site-packages/toga_gtk/app.py", line 93, in gtk_startup
    self.interface.startup()
  File "/home/bsanderson11/Documents/DevHub/code/toga/venv/lib/python3.8/site-packages/toga/app.py", line 411, in startup
    self.main_window = MainWindow(title=self.formal_name, factory=self.factory)
  File "/home/bsanderson11/Documents/DevHub/code/toga/venv/lib/python3.8/site-packages/toga/app.py", line 25, in __init__
    super().__init__(
  File "/home/bsanderson11/Documents/DevHub/code/toga/venv/lib/python3.8/site-packages/toga/window.py", line 42, in __init__
    self._impl = getattr(self.factory, self._WINDOW_CLASS)(interface=self)
  File "/home/bsanderson11/Documents/DevHub/code/toga/venv/lib/python3.8/site-packages/toga_gtk/window.py", line 37, in __init__
    self.create()
  File "/home/bsanderson11/Documents/DevHub/code/toga/venv/lib/python3.8/site-packages/toga_gtk/app.py", line 31, in create
    toga_App.app.icon.bind(self.interface.factory)
  File "/home/bsanderson11/Documents/DevHub/code/toga/venv/lib/python3.8/site-packages/toga/icons.py", line 61, in bind
    self._impl = self.DEFAULT_ICON.bind(factory)
  File "/home/bsanderson11/Documents/DevHub/code/toga/venv/lib/python3.8/site-packages/toga/icons.py", line 61, in bind
    self._impl = self.DEFAULT_ICON.bind(factory)
  File "/home/bsanderson11/Documents/DevHub/code/toga/venv/lib/python3.8/site-packages/toga/icons.py", line 61, in bind
    self._impl = self.DEFAULT_ICON.bind(factory)
  [Previous line repeated 970 more times]
  File "/home/bsanderson11/Documents/DevHub/code/toga/venv/lib/python3.8/site-packages/toga/icons.py", line 41, in bind
    full_path = {
  File "/home/bsanderson11/Documents/DevHub/code/toga/venv/lib/python3.8/site-packages/toga/icons.py", line 42, in <dictcomp>
    size: self._full_path(
  File "/home/bsanderson11/Documents/DevHub/code/toga/venv/lib/python3.8/site-packages/toga/icons.py", line 80, in _full_path
    if icon_path.exists():
  File "/usr/lib/python3.8/pathlib.py", line 1383, in exists
    self.stat()
  File "/usr/lib/python3.8/pathlib.py", line 1189, in stat
    return self._accessor.stat(self)
  File "/usr/lib/python3.8/pathlib.py", line 720, in __fspath__
    return str(self)
  File "/usr/lib/python3.8/pathlib.py", line 715, in __str__
    self._str = self._format_parsed_parts(self._drv, self._root,
  File "/usr/lib/python3.8/pathlib.py", line 695, in _format_parsed_parts
    return drv + root + cls._flavour.join(parts[1:])
RecursionError: maximum recursion depth exceeded while calling a Python object
